FILE_HEADER <- "# Generated by dev script: do not edit by hand"

SCRIPT_ROOT <- "dev/generate-r-files/polars-version"

git_rev <- RcppTOML::parseTOML("src/rust/Cargo.toml")$dependencies$`polars-core`$rev

py_version <- glue::glue(
  "https://raw.githubusercontent.com/pola-rs/polars/{git_rev}/py-polars/pyproject.toml"
) |>
  readr::read_file() |>
  RcppTOML::parseTOML(fromFile = FALSE) |>
  _$project$version

# nolint start: line_length_linter
py_semver <- glue::glue(
  "https://raw.githubusercontent.com/pola-rs/polars/{git_rev}/py-polars/runtime/template/Cargo.template.toml"
) |>
  readr::read_file() |>
  RcppTOML::parseTOML(fromFile = FALSE) |>
  _$package$version

dsl_schema_hash_current <- glue::glue(
  "https://raw.githubusercontent.com/pola-rs/polars/{git_rev}/crates/polars-plan/dsl-schema-hashes.json"
) |>
  readr::read_file() |>
  charToRaw() |>
  tools::sha256sum(bytes = _)

dsl_schema_hash_py <- glue::glue(
  "https://raw.githubusercontent.com/pola-rs/polars/refs/tags/py-{py_semver}/crates/polars-plan/dsl-schema-hashes.json"
) |>
  readr::read_file() |>
  charToRaw() |>
  tools::sha256sum(bytes = _)
# nolint end

template <- readr::read_file(
  file.path(SCRIPT_ROOT, "templates", "polars-version.R.txt")
)
glue::glue(FILE_HEADER, "\n\n", template, .open = "{{", .close = "}}", .trim = FALSE) |>
  readr::write_file("R/generated-polars-version.R")
