version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci: "

  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup/action.yaml"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci: "

  - package-ecosystem: "cargo"
    directory: "/src/rust"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
