
### Basic information
site_name: polars
theme:
  name: material

  # Dark mode toggle
  palette:
    - media: '(prefers-color-scheme: light)' #
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)' #
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
    - toc:
        baselevel: 2
        toc_depth: 1

### Repo information
repo_url: https://github.com/pola-rs/r-polars
repo_name: polars

### Plugins
plugins:
  - search

### Navigation tree
nav:
  - Home: README.md
  - Reference:
    - DataFrame:
        - reference/DataFrame.md
        - reference/DataFrame_as_data_frame.md
        - reference/DataFrame_clone.md
        - reference/DataFrame_columns.md
        - reference/DataFrame_dtypes.md
        - reference/DataFrame_estimated_size.md
        - reference/DataFrame_first.md
        - reference/DataFrame_get_column.md
        - reference/DataFrame_get_columns.md
        - reference/DataFrame_groupby.md
        - reference/DataFrame_height.md
        - reference/DataFrame_join.md
        - reference/DataFrame_last.md
        - reference/DataFrame_lazy.md
        - reference/DataFrame_limit.md
        - reference/DataFrame_max.md
        - reference/DataFrame_mean.md
        - reference/DataFrame_median.md
        - reference/DataFrame_min.md
        - reference/DataFrame_null_count.md
        - reference/DataFrame_print.md
        - reference/DataFrame_reverse.md
        - reference/DataFrame_select.md
        - reference/DataFrame_shape.md
        - reference/DataFrame_slice.md
        - reference/DataFrame_std.md
        - reference/DataFrame_sum.md
        - reference/DataFrame_tail.md
        - reference/DataFrame_to_series.md
        - reference/DataFrame_to_Struct_unnest.md
        - reference/DataFrame_var.md
        - reference/DataFrame_width.md
        - reference/DataFrame_with_columns.md
    - LazyFrame:
        - reference/LazyFrame_collect.md
        - reference/LazyFrame_collect_background.md
        - reference/LazyFrame_describe_optimized_plan.md
        - reference/LazyFrame_describe_plan.md
        - reference/LazyFrame_filter.md
        - reference/LazyFrame_first.md
        - reference/LazyFrame_groupby.md
        - reference/LazyFrame_join.md
        - reference/LazyFrame_last.md
        - reference/LazyFrame_limit.md
        - reference/LazyFrame_max.md
        - reference/LazyFrame_mean.md
        - reference/LazyFrame_median.md
        - reference/LazyFrame_min.md
        - reference/LazyFrame_print.md
        - reference/LazyFrame_reverse.md
        - reference/LazyFrame_select.md
        - reference/LazyFrame_slice.md
        - reference/LazyFrame_std.md
        - reference/LazyFrame_sum.md
        - reference/LazyFrame_tail.md
        - reference/LazyFrame_var.md
        - reference/LazyFrame_with_column.md
        - reference/LazyFrame_with_columns.md
    - macro_add_syntax_check_to: reference/
    - Series:
        - reference/Series.md
        - reference/Series_abs.md
        - reference/Series_add.md
        - reference/Series_alias.md
        - reference/Series_all.md
        - reference/Series_any.md
        - reference/Series_append.md
        - reference/Series_apply.md
        - reference/Series_arg_max.md
        - reference/Series_arg_min.md
        - reference/Series_arr.md
        - reference/Series_ceil.md
        - reference/Series_chunk_lengths.md
        - reference/Series_clone.md
        - reference/Series_compare.md
        - reference/Series_cumsum.md
        - reference/Series_div.md
        - reference/Series_dtype.md
        - reference/Series_expr.md
        - reference/Series_floor.md
        - reference/Series_is_numeric.md
        - reference/Series_is_sorted.md
        - reference/Series_len.md
        - reference/Series_max.md
        - reference/Series_min.md
        - reference/Series_mul.md
        - reference/Series_name.md
        - reference/Series_print.md
        - reference/Series_rem.md
        - reference/Series_rename.md
        - reference/Series_rep.md
        - reference/Series_series_equal.md
        - reference/Series_set_sorted.md
        - reference/Series_shape.md
        - reference/Series_sort.md
        - reference/Series_std.md
        - reference/Series_sub.md
        - reference/Series_sum.md
        - reference/Series_to_frames.md
        - reference/Series_to_lit.md
        - reference/Series_to_r.md
        - reference/Series_value_count.md
        - reference/Series_var.md
    - Other:
        - reference/all.md
        - reference/and_then.md
        - reference/arr_arg_max.md
        - reference/arr_arg_min.md
        - reference/arr_concat.md
        - reference/arr_contains.md
        - reference/arr_diff.md
        - reference/arr_eval.md
        - reference/arr_first.md
        - reference/arr_get.md
        - reference/arr_head.md
        - reference/arr_join.md
        - reference/arr_last.md
        - reference/arr_lengths.md
        - reference/arr_max.md
        - reference/arr_mean.md
        - reference/arr_min.md
        - reference/arr_reverse.md
        - reference/arr_shift.md
        - reference/arr_slice.md
        - reference/arr_sort.md
        - reference/arr_sum.md
        - reference/arr_tail.md
        - reference/arr_take.md
        - reference/arr_to_struct.md
        - reference/arr_unique.md
        - reference/c.Series.md
        - reference/cash-set-.DataFrame.md
        - reference/check_no_missing_args.md
        - reference/check_tz_to_result.md
        - reference/clone_env_one_level_deep.md
        - reference/coalesce.md
        - reference/col.md
        - reference/construct_DataTypeVector.md
        - reference/construct_ProtoExprArray.md
        - reference/DataType.md
        - reference/DataType_constructors.md
        - reference/DataType_new.md
        - reference/docs_translations.md
        - reference/dot-DollarNames.DataFrame.md
        - reference/dot-DollarNames.Expr.md
        - reference/dot-DollarNames.GroupBy.md
        - reference/dot-DollarNames.LazyFrame.md
        - reference/dot-DollarNames.PolarsBackgroundHandle.md
        - reference/dot-DollarNames.Series.md
        - reference/dot-DollarNames.VecDataFrame.md
        - reference/dot-DollarNames.When.md
        - reference/dot-DollarNames.WhenThen.md
        - reference/dot-DollarNames.WhenThenThen.md
        - reference/dot-pr.md
        - reference/element.md
        - reference/Err.md
        - reference/Expr-cash-print-open-paren-close-paren.md
        - reference/Expr.md
        - reference/Expr_abs.md
        - reference/Expr_add.md
        - reference/Expr_agg_groups.md
        - reference/Expr_alias.md
        - reference/Expr_all.md
        - reference/Expr_and.md
        - reference/Expr_any.md
        - reference/Expr_append.md
        - reference/Expr_apply.md
        - reference/Expr_arccos.md
        - reference/Expr_arccosh.md
        - reference/Expr_arcsin.md
        - reference/Expr_arcsinh.md
        - reference/Expr_arctan.md
        - reference/Expr_arctanh.md
        - reference/Expr_arg_max.md
        - reference/Expr_arg_min.md
        - reference/Expr_arg_sort.md
        - reference/Expr_arg_unique.md
        - reference/Expr_arr.md
        - reference/Expr_backward_fill.md
        - reference/Expr_bin.md
        - reference/Expr_cast.md
        - reference/Expr_cat.md
        - reference/Expr_ceil.md
        - reference/Expr_clip.md
        - reference/Expr_cos.md
        - reference/Expr_cosh.md
        - reference/Expr_count.md
        - reference/Expr_cumcount.md
        - reference/Expr_cummin.md
        - reference/Expr_cumprod.md
        - reference/Expr_cumsum.md
        - reference/Expr_cumulative_eval.md
        - reference/Expr_diff.md
        - reference/Expr_div.md
        - reference/Expr_dot.md
        - reference/Expr_drop_nans.md
        - reference/Expr_drop_nulls.md
        - reference/Expr_dt.md
        - reference/Expr_entropy.md
        - reference/Expr_eq.md
        - reference/Expr_ewm_mean_std_var.md
        - reference/Expr_exclude.md
        - reference/Expr_exp.md
        - reference/Expr_explode.md
        - reference/Expr_extend_constant.md
        - reference/Expr_extend_expr.md
        - reference/Expr_fill_nan.md
        - reference/Expr_fill_null.md
        - reference/Expr_filter.md
        - reference/Expr_first.md
        - reference/Expr_floor.md
        - reference/Expr_forward_fill.md
        - reference/Expr_gt.md
        - reference/Expr_gt_eq.md
        - reference/Expr_hash.md
        - reference/Expr_head.md
        - reference/Expr_inspect.md
        - reference/Expr_interpolate.md
        - reference/Expr_is_between.md
        - reference/Expr_is_duplicated.md
        - reference/Expr_is_finite.md
        - reference/Expr_is_first.md
        - reference/Expr_is_in.md
        - reference/Expr_is_infinite.md
        - reference/Expr_is_nan.md
        - reference/Expr_is_not.md
        - reference/Expr_is_not_nan.md
        - reference/Expr_is_not_null.md
        - reference/Expr_is_null.md
        - reference/Expr_is_unique.md
        - reference/Expr_keep_name.md
        - reference/Expr_kurtosis.md
        - reference/Expr_last.md
        - reference/Expr_limit.md
        - reference/Expr_list.md
        - reference/Expr_lit_to_df.md
        - reference/Expr_lit_to_s.md
        - reference/Expr_log.md
        - reference/Expr_log10.md
        - reference/Expr_lt.md
        - reference/Expr_lt_eq.md
        - reference/Expr_map.md
        - reference/Expr_map_alias.md
        - reference/Expr_max.md
        - reference/Expr_mean.md
        - reference/Expr_median.md
        - reference/Expr_meta.md
        - reference/Expr_min.md
        - reference/Expr_mode.md
        - reference/Expr_mul.md
        - reference/Expr_n_unique.md
        - reference/Expr_nan_max.md
        - reference/Expr_nan_min.md
        - reference/Expr_neq.md
        - reference/Expr_null_count.md
        - reference/Expr_or.md
        - reference/Expr_over.md
        - reference/Expr_pct_change.md
        - reference/Expr_pow.md
        - reference/Expr_product.md
        - reference/Expr_quantile.md
        - reference/Expr_rank.md
        - reference/Expr_rechunk.md
        - reference/Expr_reinterpret.md
        - reference/Expr_rep.md
        - reference/Expr_rep_extend.md
        - reference/Expr_repeat_by.md
        - reference/Expr_reshape.md
        - reference/Expr_rolling_max.md
        - reference/Expr_rolling_mean.md
        - reference/Expr_rolling_median.md
        - reference/Expr_rolling_min.md
        - reference/Expr_rolling_quantile.md
        - reference/Expr_rolling_skew.md
        - reference/Expr_rolling_std.md
        - reference/Expr_rolling_sum.md
        - reference/Expr_rolling_var.md
        - reference/Expr_round.md
        - reference/Expr_rpow.md
        - reference/Expr_sample.md
        - reference/Expr_search_sorted.md
        - reference/Expr_set_sorted.md
        - reference/Expr_shift.md
        - reference/Expr_shift_and_fill.md
        - reference/Expr_shrink_dtype.md
        - reference/Expr_shuffle.md
        - reference/Expr_sign.md
        - reference/Expr_sin.md
        - reference/Expr_sinh.md
        - reference/Expr_skew.md
        - reference/Expr_slice.md
        - reference/Expr_sort.md
        - reference/Expr_sort_by.md
        - reference/Expr_sqrt.md
        - reference/Expr_std.md
        - reference/Expr_str.md
        - reference/Expr_struct.md
        - reference/Expr_sub.md
        - reference/Expr_sum.md
        - reference/Expr_tail.md
        - reference/Expr_take.md
        - reference/Expr_take_every.md
        - reference/Expr_tan.md
        - reference/Expr_tanh.md
        - reference/Expr_to_physical.md
        - reference/Expr_to_r.md
        - reference/Expr_to_struct.md
        - reference/Expr_top_k.md
        - reference/Expr_unique.md
        - reference/Expr_unique_counts.md
        - reference/Expr_upper_lower_bound.md
        - reference/Expr_value_counts.md
        - reference/Expr_var.md
        - reference/Expr_xor.md
        - reference/ExprBin_contains.md
        - reference/ExprBin_decode.md
        - reference/ExprBin_encode.md
        - reference/ExprBin_ends_with.md
        - reference/ExprBin_starts_with.md
        - reference/ExprCat_set_ordering.md
        - reference/ExprDT_cast_time_unit.md
        - reference/ExprDT_combine.md
        - reference/ExprDT_convert_time_zone.md
        - reference/ExprDT_day.md
        - reference/ExprDT_days.md
        - reference/ExprDT_epoch.md
        - reference/ExprDT_hour.md
        - reference/ExprDT_hours.md
        - reference/ExprDT_iso_year.md
        - reference/ExprDT_microsecond.md
        - reference/ExprDT_microseconds.md
        - reference/ExprDT_millisecond.md
        - reference/ExprDT_milliseconds.md
        - reference/ExprDT_minute.md
        - reference/ExprDT_minutes.md
        - reference/ExprDT_month.md
        - reference/ExprDT_nanosecond.md
        - reference/ExprDT_nanoseconds.md
        - reference/ExprDT_offset_by.md
        - reference/ExprDT_ordinal_day.md
        - reference/ExprDT_quarter.md
        - reference/ExprDT_replace_time_zone.md
        - reference/ExprDT_round.md
        - reference/ExprDT_second.md
        - reference/ExprDT_seconds.md
        - reference/ExprDT_strftime.md
        - reference/ExprDT_timestamp.md
        - reference/ExprDT_truncate.md
        - reference/ExprDT_tz_localize.md
        - reference/ExprDT_week.md
        - reference/ExprDT_weekday.md
        - reference/ExprDT_with_time_unit.md
        - reference/ExprDT_year.md
        - reference/ExprMeta_eq.md
        - reference/ExprMeta_has_multiple_outputs.md
        - reference/ExprMeta_is_regex_projection.md
        - reference/ExprMeta_neq.md
        - reference/ExprMeta_output_name.md
        - reference/ExprMeta_pop.md
        - reference/ExprMeta_root_names.md
        - reference/ExprMeta_undo_aliases.md
        - reference/ExprStr_concat.md
        - reference/ExprStr_contains.md
        - reference/ExprStr_count_match.md
        - reference/ExprStr_decode.md
        - reference/ExprStr_encode.md
        - reference/ExprStr_ends_with.md
        - reference/ExprStr_explode.md
        - reference/ExprStr_extract.md
        - reference/ExprStr_extract_all.md
        - reference/ExprStr_json_extract.md
        - reference/ExprStr_json_path_match.md
        - reference/ExprStr_lengths.md
        - reference/ExprStr_ljust.md
        - reference/ExprStr_lstrip.md
        - reference/ExprStr_n_chars.md
        - reference/ExprStr_parse_int.md
        - reference/ExprStr_replace.md
        - reference/ExprStr_replace_all.md
        - reference/ExprStr_rjust.md
        - reference/ExprStr_rstrip.md
        - reference/ExprStr_slice.md
        - reference/ExprStr_split.md
        - reference/ExprStr_split_exact.md
        - reference/ExprStr_splitn.md
        - reference/ExprStr_starts_with.md
        - reference/ExprStr_strip.md
        - reference/ExprStr_strptime.md
        - reference/ExprStr_to_lowercase.md
        - reference/ExprStr_to_uppercase.md
        - reference/ExprStr_zfill.md
        - reference/ExprStruct_field.md
        - reference/ExprStruct_rename_fields.md
        - reference/extendr_method_to_pure_functions.md
        - reference/extra_auto_completion.md
        - reference/filter-open-paren-close-paren.md
        - reference/get_method_usages.md
        - reference/GroupBy_agg.md
        - reference/GroupBy_as_data_frame.md
        - reference/GroupBy_first.md
        - reference/GroupBy_last.md
        - reference/GroupBy_max.md
        - reference/GroupBy_mean.md
        - reference/GroupBy_median.md
        - reference/GroupBy_min.md
        - reference/GroupBy_null_count.md
        - reference/GroupBy_std.md
        - reference/GroupBy_sum.md
        - reference/GroupBy_var.md
        - reference/is_DataFrame_data_input.md
        - reference/is_err.md
        - reference/is_ok.md
        - reference/is_polars_dtype.md
        - reference/is_result.md
        - reference/is_schema.md
        - reference/l_to_vdf.md
        - reference/lazy_csv_reader.md
        - reference/LazyGroupBy_agg.md
        - reference/LazyGroupBy_apply.md
        - reference/LazyGroupBy_head.md
        - reference/LazyGroupBy_print.md
        - reference/LazyGroupBy_tail.md
        - reference/length.Series.md
        - reference/macro_new_subnamespace.md
        - reference/map.md
        - reference/map_err.md
        - reference/max.md
        - reference/mem_address.md
        - reference/method_as_property.md
        - reference/min.md
        - reference/move_env_elements.md
        - reference/nanoarrow.md
        - reference/ncol.DataFrame.md
        - reference/ncol.LazyFrame.md
        - reference/nrow.DataFrame.md
        - reference/nrow.LazyFrame.md
        - reference/object.md
        - reference/Ok.md
        - reference/or_else.md
        - reference/pcase.md
        - reference/pl-cash-from_arrow.md
        - reference/pl.md
        - reference/pl_concat.md
        - reference/pl_date_range.md
        - reference/pl_Datetime.md
        - reference/pl_Field.md
        - reference/pl_List.md
        - reference/pl_PTime.md
        - reference/pl_select.md
        - reference/pl_Struct.md
        - reference/polars_options.md
        - reference/polars_runtime_flags.md
        - reference/PolarsBackgroundHandle_is_exhausted.md
        - reference/PolarsBackgroundHandle_join.md
        - reference/prepare_alpha.md
        - reference/print-open-paren-close-paren.md
        - reference/print.Expr.md
        - reference/print.GroupBy.md
        - reference/print.LazyFrame.md
        - reference/print.LazyGroupBy.md
        - reference/print.PolarsBackgroundHandle.md
        - reference/print.PTime.md
        - reference/print.RField.md
        - reference/print.RPolarsDataType.md
        - reference/print.When.md
        - reference/print.WhenThen.md
        - reference/print.WhenThenThen.md
        - reference/print_env.md
        - reference/pstop.md
        - reference/read_csv_.md
        - reference/replace_private_with_pub_methods.md
        - reference/restruct_list.md
        - reference/RField_name.md
        - reference/RField_print.md
        - reference/same_outer_datatype.md
        - reference/scan_arrow_ipc.md
        - reference/scan_parquet.md
        - reference/str_string.md
        - reference/struct.md
        - reference/sum.md
        - reference/to_list.md
        - reference/unAsIs.md
        - reference/unwrap.md
        - reference/verify_method_call.md
        - reference/when_then_otherwise.md
        - reference/wrap_e.md
        - reference/wrap_e_result.md
        - reference/wrap_elist_result.md
        - reference/wrap_proto_schema.md
        - reference/wrap_s.md
  - License: LICENSE.md

