FILE_HEADER <- "# Generated by dev script: do not edit by hand"

SCRIPT_ROOT <- "dev/generate-r-files"

generate_file <- function(data_file, template_file, dest_file) {
  class_names <- readr::read_tsv(data_file, show_col_types = FALSE)
  template <- readr::read_file(template_file)

  dest_body <- glue::glue_data(class_names, template, .open = "{{", .close = "}}") |>
    paste0(collapse = "\n\n")

  glue::glue("{FILE_HEADER}\n\n{dest_body}\n\n") |>
    readr::write_file(dest_file)
}

# Generate files
generate_file(
  data_file = file.path(SCRIPT_ROOT, "data", "class-names.tsv"),
  template_file = file.path(SCRIPT_ROOT, "templates", "s3methods-dollar.R.txt"),
  dest_file = file.path("R", "generated-s3methods-dollar.R")
)

generate_file(
  data_file = file.path(SCRIPT_ROOT, "data", "series-namespace-names.tsv"),
  template_file = file.path(SCRIPT_ROOT, "templates", "s3methods-series-namespace-dollar.R.txt"),
  dest_file = file.path("R", "generated-s3methods-series-namespace-dollar.R")
)
