DEST_FILE <- "R/generated-s3methods-dollar.R"
SCRIPT_ROOT <- "dev/generate-r-files"

CLASS_NAME_SOURCE_FILE <- file.path(SCRIPT_ROOT, "data", "class-names.tsv")
TEMPLATE_FILE <- file.path(SCRIPT_ROOT, "templates", "s3methods-dollar.R.txt")

FILE_HEADER <- "# Generated by dev script: do not edit by hand"

class_names <- readr::read_tsv(CLASS_NAME_SOURCE_FILE, show_col_types = FALSE)
template <- readr::read_file(TEMPLATE_FILE)

dest_body <- glue::glue_data(class_names, template, .open = "{{", .close = "}}") |>
  paste0(collapse = "\n\n")

glue::glue("{FILE_HEADER}\n\n{dest_body}\n\n") |>
  readr::write_file(DEST_FILE)
