# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib neopolars, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}


### wrapper functions for PlRDataFrame

PlRDataFrame_print <- function(self) {
  function() {
  invisible(.Call(savvy_PlRDataFrame_print__impl, self))
  }
}

PlRDataFrame_to_struct <- function(self) {
  function(name) {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRDataFrame_to_struct__impl, self, name))
  }
}

.savvy_wrap_PlRDataFrame <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$print <- PlRDataFrame_print(ptr)
  e$to_struct <- PlRDataFrame_to_struct(ptr)
  
  class(e) <- "PlRDataFrame"
  e
}



PlRDataFrame <- new.env(parent = emptyenv())

### associated functions for PlRDataFrame

PlRDataFrame$init <- function(columns) {
  .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_init__impl, columns))
}


### wrapper functions for PlRDataType

PlRDataType_print <- function(self) {
  function() {
  invisible(.Call(savvy_PlRDataType_print__impl, self))
  }
}

.savvy_wrap_PlRDataType <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$print <- PlRDataType_print(ptr)
  
  class(e) <- "PlRDataType"
  e
}



PlRDataType <- new.env(parent = emptyenv())

### associated functions for PlRDataType

PlRDataType$new_from_name <- function(name) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_from_name__impl, name))
}

PlRDataType$new_categorical <- function(ordering) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_categorical__impl, ordering))
}

PlRDataType$new_datetime <- function(time_unit, time_zone = NULL) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_datetime__impl, time_unit, time_zone))
}

PlRDataType$new_duration <- function(time_unit) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_duration__impl, time_unit))
}


### wrapper functions for PlRSeries

PlRSeries_print <- function(self) {
  function() {
  invisible(.Call(savvy_PlRSeries_print__impl, self))
  }
}

PlRSeries_struct_unnest <- function(self) {
  function() {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRSeries_struct_unnest__impl, self))
  }
}

PlRSeries_clone <- function(self) {
  function() {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_clone__impl, self))
  }
}

PlRSeries_name <- function(self) {
  function() {
  .Call(savvy_PlRSeries_name__impl, self)
  }
}

PlRSeries_rename <- function(self) {
  function(name) {
  invisible(.Call(savvy_PlRSeries_rename__impl, self, name))
  }
}

PlRSeries_cast <- function(self) {
  function(dtype, strict) {
    dtype <- .savvy_extract_ptr(dtype, "PlRDataType")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_cast__impl, self, dtype, strict))
  }
}

PlRSeries_add <- function(self) {
  function(other) {
    other <- .savvy_extract_ptr(other, "PlRSeries")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_add__impl, self, other))
  }
}

PlRSeries_sub <- function(self) {
  function(other) {
    other <- .savvy_extract_ptr(other, "PlRSeries")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_sub__impl, self, other))
  }
}

PlRSeries_div <- function(self) {
  function(other) {
    other <- .savvy_extract_ptr(other, "PlRSeries")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_div__impl, self, other))
  }
}

PlRSeries_mul <- function(self) {
  function(other) {
    other <- .savvy_extract_ptr(other, "PlRSeries")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_mul__impl, self, other))
  }
}

PlRSeries_rem <- function(self) {
  function(other) {
    other <- .savvy_extract_ptr(other, "PlRSeries")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_rem__impl, self, other))
  }
}

.savvy_wrap_PlRSeries <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
    e$print <- PlRSeries_print(ptr)
  e$struct_unnest <- PlRSeries_struct_unnest(ptr)
  e$clone <- PlRSeries_clone(ptr)
  e$name <- PlRSeries_name(ptr)
  e$rename <- PlRSeries_rename(ptr)
  e$cast <- PlRSeries_cast(ptr)
  e$add <- PlRSeries_add(ptr)
  e$sub <- PlRSeries_sub(ptr)
  e$div <- PlRSeries_div(ptr)
  e$mul <- PlRSeries_mul(ptr)
  e$rem <- PlRSeries_rem(ptr)
  
  class(e) <- "PlRSeries"
  e
}



PlRSeries <- new.env(parent = emptyenv())

### associated functions for PlRSeries

PlRSeries$new_empty <- function(name, dtype = NULL) {
  dtype <- .savvy_extract_ptr(dtype, "PlRDataType")
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_empty__impl, name, dtype))
}

PlRSeries$new_f64 <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_f64__impl, name, values))
}

PlRSeries$new_i32 <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i32__impl, name, values))
}

PlRSeries$new_bool <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_bool__impl, name, values))
}

PlRSeries$new_str <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_str__impl, name, values))
}

PlRSeries$new_categorical <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_categorical__impl, name, values))
}

PlRSeries$new_series_list <- function(name, values) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_series_list__impl, name, values))
}


