# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib neopolars, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_neopolars__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_neopolars__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


`all_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_all_horizontal__impl, `exprs`))
}


`any_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_any_horizontal__impl, `exprs`))
}


`max_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_max_horizontal__impl, `exprs`))
}


`min_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_min_horizontal__impl, `exprs`))
}


`sum_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_sum_horizontal__impl, `exprs`))
}


`mean_horizontal` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_mean_horizontal__impl, `exprs`))
}


`concat_df` <- function(`dfs`) {
  .savvy_wrap_PlRDataFrame(.Call(savvy_concat_df__impl, `dfs`))
}


`concat_series` <- function(`series`) {
  .savvy_wrap_PlRSeries(.Call(savvy_concat_series__impl, `series`))
}


`as_struct` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_as_struct__impl, `exprs`))
}


`datetime` <- function(`year`, `month`, `day`, `time_unit`, `ambiguous`, `hour` = NULL, `minute` = NULL, `second` = NULL, `microsecond` = NULL, `time_zone` = NULL) {
  `year` <- .savvy_extract_ptr(`year`, "PlRExpr")
  `month` <- .savvy_extract_ptr(`month`, "PlRExpr")
  `day` <- .savvy_extract_ptr(`day`, "PlRExpr")
  `ambiguous` <- .savvy_extract_ptr(`ambiguous`, "PlRExpr")
  `hour` <- .savvy_extract_ptr(`hour`, "PlRExpr")
  `minute` <- .savvy_extract_ptr(`minute`, "PlRExpr")
  `second` <- .savvy_extract_ptr(`second`, "PlRExpr")
  `microsecond` <- .savvy_extract_ptr(`microsecond`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_datetime__impl, `year`, `month`, `day`, `time_unit`, `ambiguous`, `hour`, `minute`, `second`, `microsecond`, `time_zone`))
}


`duration` <- function(`time_unit`, `weeks` = NULL, `days` = NULL, `hours` = NULL, `minutes` = NULL, `seconds` = NULL, `milliseconds` = NULL, `microseconds` = NULL, `nanoseconds` = NULL) {
  `weeks` <- .savvy_extract_ptr(`weeks`, "PlRExpr")
  `days` <- .savvy_extract_ptr(`days`, "PlRExpr")
  `hours` <- .savvy_extract_ptr(`hours`, "PlRExpr")
  `minutes` <- .savvy_extract_ptr(`minutes`, "PlRExpr")
  `seconds` <- .savvy_extract_ptr(`seconds`, "PlRExpr")
  `milliseconds` <- .savvy_extract_ptr(`milliseconds`, "PlRExpr")
  `microseconds` <- .savvy_extract_ptr(`microseconds`, "PlRExpr")
  `nanoseconds` <- .savvy_extract_ptr(`nanoseconds`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_duration__impl, `time_unit`, `weeks`, `days`, `hours`, `minutes`, `seconds`, `milliseconds`, `microseconds`, `nanoseconds`))
}


`field` <- function(`names`) {
  .savvy_wrap_PlRExpr(.Call(savvy_field__impl, `names`))
}


`coalesce` <- function(`exprs`) {
  .savvy_wrap_PlRExpr(.Call(savvy_coalesce__impl, `exprs`))
}


`col` <- function(`name`) {
  .savvy_wrap_PlRExpr(.Call(savvy_col__impl, `name`))
}


`cols` <- function(`names`) {
  .savvy_wrap_PlRExpr(.Call(savvy_cols__impl, `names`))
}


`dtype_cols` <- function(`dtypes`) {
  .savvy_wrap_PlRExpr(.Call(savvy_dtype_cols__impl, `dtypes`))
}


`index_cols` <- function(`indices`) {
  .savvy_wrap_PlRExpr(.Call(savvy_index_cols__impl, `indices`))
}


`first` <- function() {
  .savvy_wrap_PlRExpr(.Call(savvy_first__impl))
}


`last` <- function() {
  .savvy_wrap_PlRExpr(.Call(savvy_last__impl))
}


`lit_from_bool` <- function(`value`) {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_bool__impl, `value`))
}


`lit_from_i32` <- function(`value`) {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_i32__impl, `value`))
}


`lit_from_f64` <- function(`value`) {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_f64__impl, `value`))
}


`lit_from_str` <- function(`value`) {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_str__impl, `value`))
}


`lit_from_raw` <- function(`value`) {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_raw__impl, `value`))
}


`lit_null` <- function() {
  .savvy_wrap_PlRExpr(.Call(savvy_lit_null__impl))
}


`lit_from_series` <- function(`value`) {
  `value` <- .savvy_extract_ptr(`value`, "PlRSeries")
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_series__impl, `value`))
}


`lit_from_series_first` <- function(`value`) {
  `value` <- .savvy_extract_ptr(`value`, "PlRSeries")
  .savvy_wrap_PlRExpr(.Call(savvy_lit_from_series_first__impl, `value`))
}


`concat_list` <- function(`s`) {
  .savvy_wrap_PlRExpr(.Call(savvy_concat_list__impl, `s`))
}


`concat_df_diagonal` <- function(`dfs`) {
  .savvy_wrap_PlRDataFrame(.Call(savvy_concat_df_diagonal__impl, `dfs`))
}


`concat_df_horizontal` <- function(`dfs`) {
  .savvy_wrap_PlRDataFrame(.Call(savvy_concat_df_horizontal__impl, `dfs`))
}


`concat_lf` <- function(`lfs`, `rechunk`, `parallel`, `to_supertypes`) {
  .savvy_wrap_PlRLazyFrame(.Call(savvy_concat_lf__impl, `lfs`, `rechunk`, `parallel`, `to_supertypes`))
}


`concat_lf_horizontal` <- function(`lfs`, `parallel`) {
  .savvy_wrap_PlRLazyFrame(.Call(savvy_concat_lf_horizontal__impl, `lfs`, `parallel`))
}


`concat_lf_diagonal` <- function(`lfs`, `rechunk`, `parallel`, `to_supertypes`) {
  .savvy_wrap_PlRLazyFrame(.Call(savvy_concat_lf_diagonal__impl, `lfs`, `rechunk`, `parallel`, `to_supertypes`))
}


`int_range` <- function(`start`, `end`, `step`, `dtype`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  `dtype` <- .savvy_extract_ptr(`dtype`, "PlRDataType")
  .savvy_wrap_PlRExpr(.Call(savvy_int_range__impl, `start`, `end`, `step`, `dtype`))
}


`int_ranges` <- function(`start`, `end`, `step`, `dtype`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  `step` <- .savvy_extract_ptr(`step`, "PlRExpr")
  `dtype` <- .savvy_extract_ptr(`dtype`, "PlRDataType")
  .savvy_wrap_PlRExpr(.Call(savvy_int_ranges__impl, `start`, `end`, `step`, `dtype`))
}


`date_range` <- function(`start`, `end`, `interval`, `closed`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_date_range__impl, `start`, `end`, `interval`, `closed`))
}


`date_ranges` <- function(`start`, `end`, `interval`, `closed`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_date_ranges__impl, `start`, `end`, `interval`, `closed`))
}


`datetime_range` <- function(`start`, `end`, `every`, `closed`, `time_unit` = NULL, `time_zone` = NULL) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_datetime_range__impl, `start`, `end`, `every`, `closed`, `time_unit`, `time_zone`))
}


`datetime_ranges` <- function(`start`, `end`, `every`, `closed`, `time_unit` = NULL, `time_zone` = NULL) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_datetime_ranges__impl, `start`, `end`, `every`, `closed`, `time_unit`, `time_zone`))
}


`time_range` <- function(`start`, `end`, `every`, `closed`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_time_range__impl, `start`, `end`, `every`, `closed`))
}


`time_ranges` <- function(`start`, `end`, `every`, `closed`) {
  `start` <- .savvy_extract_ptr(`start`, "PlRExpr")
  `end` <- .savvy_extract_ptr(`end`, "PlRExpr")
  .savvy_wrap_PlRExpr(.Call(savvy_time_ranges__impl, `start`, `end`, `every`, `closed`))
}


`when` <- function(`condition`) {
  `condition` <- .savvy_extract_ptr(`condition`, "PlRExpr")
  .savvy_wrap_PlRWhen(.Call(savvy_when__impl, `condition`))
}

### wrapper functions for PlRChainedThen

`PlRChainedThen_when` <- function(self) {
  function(`condition`) {
    `condition` <- .savvy_extract_ptr(`condition`, "PlRExpr")
    .savvy_wrap_PlRChainedWhen(.Call(savvy_PlRChainedThen_when__impl, `self`, `condition`))
  }
}

`PlRChainedThen_otherwise` <- function(self) {
  function(`statement`) {
    `statement` <- .savvy_extract_ptr(`statement`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRChainedThen_otherwise__impl, `self`, `statement`))
  }
}

`.savvy_wrap_PlRChainedThen` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`when` <- `PlRChainedThen_when`(ptr)
  e$`otherwise` <- `PlRChainedThen_otherwise`(ptr)

  class(e) <- c("PlRChainedThen", "savvy_neopolars__sealed")
  e
}



`PlRChainedThen` <- new.env(parent = emptyenv())

### associated functions for PlRChainedThen



class(`PlRChainedThen`) <- c("PlRChainedThen__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRChainedThen__bundle` <- function(x, ...) {
  cat('PlRChainedThen')
}

### wrapper functions for PlRChainedWhen

`PlRChainedWhen_then` <- function(self) {
  function(`statement`) {
    `statement` <- .savvy_extract_ptr(`statement`, "PlRExpr")
    .savvy_wrap_PlRChainedThen(.Call(savvy_PlRChainedWhen_then__impl, `self`, `statement`))
  }
}

`.savvy_wrap_PlRChainedWhen` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`then` <- `PlRChainedWhen_then`(ptr)

  class(e) <- c("PlRChainedWhen", "savvy_neopolars__sealed")
  e
}



`PlRChainedWhen` <- new.env(parent = emptyenv())

### associated functions for PlRChainedWhen



class(`PlRChainedWhen`) <- c("PlRChainedWhen__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRChainedWhen__bundle` <- function(x, ...) {
  cat('PlRChainedWhen')
}

### wrapper functions for PlRDataFrame

`PlRDataFrame_print` <- function(self) {
  function() {
    invisible(.Call(savvy_PlRDataFrame_print__impl, `self`))
  }
}

`PlRDataFrame_get_columns` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_get_columns__impl, `self`)
  }
}

`PlRDataFrame_slice` <- function(self) {
  function(`offset`, `length` = NULL) {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_slice__impl, `self`, `offset`, `length`))
  }
}

`PlRDataFrame_head` <- function(self) {
  function(`n`) {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_head__impl, `self`, `n`))
  }
}

`PlRDataFrame_tail` <- function(self) {
  function(`n`) {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_tail__impl, `self`, `n`))
  }
}

`PlRDataFrame_columns` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_columns__impl, `self`)
  }
}

`PlRDataFrame_set_column_names` <- function(self) {
  function(`names`) {
    invisible(.Call(savvy_PlRDataFrame_set_column_names__impl, `self`, `names`))
  }
}

`PlRDataFrame_dtypes` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_dtypes__impl, `self`)
  }
}

`PlRDataFrame_shape` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_shape__impl, `self`)
  }
}

`PlRDataFrame_height` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_height__impl, `self`)
  }
}

`PlRDataFrame_width` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_width__impl, `self`)
  }
}

`PlRDataFrame_to_series` <- function(self) {
  function(`index`) {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRDataFrame_to_series__impl, `self`, `index`))
  }
}

`PlRDataFrame_equals` <- function(self) {
  function(`other`, `null_equal`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRDataFrame")
    .Call(savvy_PlRDataFrame_equals__impl, `self`, `other`, `null_equal`)
  }
}

`PlRDataFrame_clone` <- function(self) {
  function() {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_clone__impl, `self`))
  }
}

`PlRDataFrame_lazy` <- function(self) {
  function() {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRDataFrame_lazy__impl, `self`))
  }
}

`PlRDataFrame_to_struct` <- function(self) {
  function(`name`) {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRDataFrame_to_struct__impl, `self`, `name`))
  }
}

`PlRDataFrame_n_chunks` <- function(self) {
  function() {
    .Call(savvy_PlRDataFrame_n_chunks__impl, `self`)
  }
}

`PlRDataFrame_rechunk` <- function(self) {
  function() {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_rechunk__impl, `self`))
  }
}

`.savvy_wrap_PlRDataFrame` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`print` <- `PlRDataFrame_print`(ptr)
  e$`get_columns` <- `PlRDataFrame_get_columns`(ptr)
  e$`slice` <- `PlRDataFrame_slice`(ptr)
  e$`head` <- `PlRDataFrame_head`(ptr)
  e$`tail` <- `PlRDataFrame_tail`(ptr)
  e$`columns` <- `PlRDataFrame_columns`(ptr)
  e$`set_column_names` <- `PlRDataFrame_set_column_names`(ptr)
  e$`dtypes` <- `PlRDataFrame_dtypes`(ptr)
  e$`shape` <- `PlRDataFrame_shape`(ptr)
  e$`height` <- `PlRDataFrame_height`(ptr)
  e$`width` <- `PlRDataFrame_width`(ptr)
  e$`to_series` <- `PlRDataFrame_to_series`(ptr)
  e$`equals` <- `PlRDataFrame_equals`(ptr)
  e$`clone` <- `PlRDataFrame_clone`(ptr)
  e$`lazy` <- `PlRDataFrame_lazy`(ptr)
  e$`to_struct` <- `PlRDataFrame_to_struct`(ptr)
  e$`n_chunks` <- `PlRDataFrame_n_chunks`(ptr)
  e$`rechunk` <- `PlRDataFrame_rechunk`(ptr)

  class(e) <- c("PlRDataFrame", "savvy_neopolars__sealed")
  e
}



`PlRDataFrame` <- new.env(parent = emptyenv())

### associated functions for PlRDataFrame

`PlRDataFrame`$`init` <- function(`columns`) {
  .savvy_wrap_PlRDataFrame(.Call(savvy_PlRDataFrame_init__impl, `columns`))
}


class(`PlRDataFrame`) <- c("PlRDataFrame__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRDataFrame__bundle` <- function(x, ...) {
  cat('PlRDataFrame')
}

### wrapper functions for PlRDataType

`PlRDataType_print` <- function(self) {
  function() {
    invisible(.Call(savvy_PlRDataType_print__impl, `self`))
  }
}

`PlRDataType__get_dtype_names` <- function(self) {
  function() {
    .Call(savvy_PlRDataType__get_dtype_names__impl, `self`)
  }
}

`PlRDataType__get_datatype_fields` <- function(self) {
  function() {
    .Call(savvy_PlRDataType__get_datatype_fields__impl, `self`)
  }
}

`PlRDataType_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRDataType_max__impl, `self`))
  }
}

`PlRDataType_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRDataType_min__impl, `self`))
  }
}

`PlRDataType_eq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRDataType")
    .Call(savvy_PlRDataType_eq__impl, `self`, `other`)
  }
}

`PlRDataType_ne` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRDataType")
    .Call(savvy_PlRDataType_ne__impl, `self`, `other`)
  }
}

`.savvy_wrap_PlRDataType` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`print` <- `PlRDataType_print`(ptr)
  e$`_get_dtype_names` <- `PlRDataType__get_dtype_names`(ptr)
  e$`_get_datatype_fields` <- `PlRDataType__get_datatype_fields`(ptr)
  e$`max` <- `PlRDataType_max`(ptr)
  e$`min` <- `PlRDataType_min`(ptr)
  e$`eq` <- `PlRDataType_eq`(ptr)
  e$`ne` <- `PlRDataType_ne`(ptr)

  class(e) <- c("PlRDataType", "savvy_neopolars__sealed")
  e
}



`PlRDataType` <- new.env(parent = emptyenv())

### associated functions for PlRDataType

`PlRDataType`$`new_from_name` <- function(`name`) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_from_name__impl, `name`))
}

`PlRDataType`$`new_decimal` <- function(`scale`, `precision` = NULL) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_decimal__impl, `scale`, `precision`))
}

`PlRDataType`$`new_datetime` <- function(`time_unit`, `time_zone` = NULL) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_datetime__impl, `time_unit`, `time_zone`))
}

`PlRDataType`$`new_duration` <- function(`time_unit`) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_duration__impl, `time_unit`))
}

`PlRDataType`$`new_categorical` <- function(`ordering`) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_categorical__impl, `ordering`))
}

`PlRDataType`$`new_enum` <- function(`categories`) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_enum__impl, `categories`))
}

`PlRDataType`$`new_list` <- function(`inner`) {
  `inner` <- .savvy_extract_ptr(`inner`, "PlRDataType")
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_list__impl, `inner`))
}

`PlRDataType`$`new_array` <- function(`inner`, `shape`) {
  `inner` <- .savvy_extract_ptr(`inner`, "PlRDataType")
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_array__impl, `inner`, `shape`))
}

`PlRDataType`$`new_struct` <- function(`fields`) {
  .savvy_wrap_PlRDataType(.Call(savvy_PlRDataType_new_struct__impl, `fields`))
}


class(`PlRDataType`) <- c("PlRDataType__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRDataType__bundle` <- function(x, ...) {
  cat('PlRDataType')
}

### wrapper functions for PlRExpr

`PlRExpr_arr_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_max__impl, `self`))
  }
}

`PlRExpr_arr_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_min__impl, `self`))
  }
}

`PlRExpr_arr_sum` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_sum__impl, `self`))
  }
}

`PlRExpr_arr_std` <- function(self) {
  function(`ddof`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_std__impl, `self`, `ddof`))
  }
}

`PlRExpr_arr_var` <- function(self) {
  function(`ddof`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_var__impl, `self`, `ddof`))
  }
}

`PlRExpr_arr_median` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_median__impl, `self`))
  }
}

`PlRExpr_arr_unique` <- function(self) {
  function(`maintain_order`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_unique__impl, `self`, `maintain_order`))
  }
}

`PlRExpr_arr_to_list` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_to_list__impl, `self`))
  }
}

`PlRExpr_arr_all` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_all__impl, `self`))
  }
}

`PlRExpr_arr_any` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_any__impl, `self`))
  }
}

`PlRExpr_arr_sort` <- function(self) {
  function(`descending`, `nulls_last`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_sort__impl, `self`, `descending`, `nulls_last`))
  }
}

`PlRExpr_arr_reverse` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_reverse__impl, `self`))
  }
}

`PlRExpr_arr_arg_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_arg_min__impl, `self`))
  }
}

`PlRExpr_arr_arg_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_arg_max__impl, `self`))
  }
}

`PlRExpr_arr_get` <- function(self) {
  function(`index`, `null_on_oob`) {
    `index` <- .savvy_extract_ptr(`index`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_get__impl, `self`, `index`, `null_on_oob`))
  }
}

`PlRExpr_arr_join` <- function(self) {
  function(`separator`, `ignore_nulls`) {
    `separator` <- .savvy_extract_ptr(`separator`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_join__impl, `self`, `separator`, `ignore_nulls`))
  }
}

`PlRExpr_arr_contains` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_contains__impl, `self`, `other`))
  }
}

`PlRExpr_arr_count_matches` <- function(self) {
  function(`expr`) {
    `expr` <- .savvy_extract_ptr(`expr`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_count_matches__impl, `self`, `expr`))
  }
}

`PlRExpr_arr_shift` <- function(self) {
  function(`n`) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_shift__impl, `self`, `n`))
  }
}

`PlRExpr_arr_n_unique` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arr_n_unique__impl, `self`))
  }
}

`PlRExpr_bin_contains` <- function(self) {
  function(`literal`) {
    `literal` <- .savvy_extract_ptr(`literal`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_contains__impl, `self`, `literal`))
  }
}

`PlRExpr_bin_ends_with` <- function(self) {
  function(`suffix`) {
    `suffix` <- .savvy_extract_ptr(`suffix`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_ends_with__impl, `self`, `suffix`))
  }
}

`PlRExpr_bin_starts_with` <- function(self) {
  function(`prefix`) {
    `prefix` <- .savvy_extract_ptr(`prefix`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_starts_with__impl, `self`, `prefix`))
  }
}

`PlRExpr_bin_hex_decode` <- function(self) {
  function(`strict`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_hex_decode__impl, `self`, `strict`))
  }
}

`PlRExpr_bin_base64_decode` <- function(self) {
  function(`strict`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_base64_decode__impl, `self`, `strict`))
  }
}

`PlRExpr_bin_hex_encode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_hex_encode__impl, `self`))
  }
}

`PlRExpr_bin_base64_encode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_base64_encode__impl, `self`))
  }
}

`PlRExpr_bin_size_bytes` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_bin_size_bytes__impl, `self`))
  }
}

`PlRExpr_cat_get_categories` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_cat_get_categories__impl, `self`))
  }
}

`PlRExpr_cat_set_ordering` <- function(self) {
  function(`ordering`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_cat_set_ordering__impl, `self`, `ordering`))
  }
}

`PlRExpr_dt_convert_time_zone` <- function(self) {
  function(`time_zone`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_convert_time_zone__impl, `self`, `time_zone`))
  }
}

`PlRExpr_dt_replace_time_zone` <- function(self) {
  function(`ambiguous`, `non_existent`, `time_zone` = NULL) {
    `ambiguous` <- .savvy_extract_ptr(`ambiguous`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_replace_time_zone__impl, `self`, `ambiguous`, `non_existent`, `time_zone`))
  }
}

`PlRExpr_dt_truncate` <- function(self) {
  function(`every`) {
    `every` <- .savvy_extract_ptr(`every`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_truncate__impl, `self`, `every`))
  }
}

`PlRExpr_dt_round` <- function(self) {
  function(`every`) {
    `every` <- .savvy_extract_ptr(`every`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_round__impl, `self`, `every`))
  }
}

`PlRExpr_dt_time` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_time__impl, `self`))
  }
}

`PlRExpr_dt_date` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_date__impl, `self`))
  }
}

`PlRExpr_dt_combine` <- function(self) {
  function(`time`, `time_unit`) {
    `time` <- .savvy_extract_ptr(`time`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_combine__impl, `self`, `time`, `time_unit`))
  }
}

`PlRExpr_dt_to_string` <- function(self) {
  function(`format`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_to_string__impl, `self`, `format`))
  }
}

`PlRExpr_dt_year` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_year__impl, `self`))
  }
}

`PlRExpr_dt_iso_year` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_iso_year__impl, `self`))
  }
}

`PlRExpr_dt_quarter` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_quarter__impl, `self`))
  }
}

`PlRExpr_dt_month` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_month__impl, `self`))
  }
}

`PlRExpr_dt_week` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_week__impl, `self`))
  }
}

`PlRExpr_dt_weekday` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_weekday__impl, `self`))
  }
}

`PlRExpr_dt_day` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_day__impl, `self`))
  }
}

`PlRExpr_dt_ordinal_day` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_ordinal_day__impl, `self`))
  }
}

`PlRExpr_dt_hour` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_hour__impl, `self`))
  }
}

`PlRExpr_dt_minute` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_minute__impl, `self`))
  }
}

`PlRExpr_dt_second` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_second__impl, `self`))
  }
}

`PlRExpr_dt_millisecond` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_millisecond__impl, `self`))
  }
}

`PlRExpr_dt_microsecond` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_microsecond__impl, `self`))
  }
}

`PlRExpr_dt_nanosecond` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_nanosecond__impl, `self`))
  }
}

`PlRExpr_dt_timestamp` <- function(self) {
  function(`time_unit`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_timestamp__impl, `self`, `time_unit`))
  }
}

`PlRExpr_dt_epoch_seconds` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_epoch_seconds__impl, `self`))
  }
}

`PlRExpr_dt_with_time_unit` <- function(self) {
  function(`time_unit`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_with_time_unit__impl, `self`, `time_unit`))
  }
}

`PlRExpr_dt_cast_time_unit` <- function(self) {
  function(`time_unit`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_cast_time_unit__impl, `self`, `time_unit`))
  }
}

`PlRExpr_dt_total_days` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_days__impl, `self`))
  }
}

`PlRExpr_dt_total_hours` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_hours__impl, `self`))
  }
}

`PlRExpr_dt_total_minutes` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_minutes__impl, `self`))
  }
}

`PlRExpr_dt_total_seconds` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_seconds__impl, `self`))
  }
}

`PlRExpr_dt_total_milliseconds` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_milliseconds__impl, `self`))
  }
}

`PlRExpr_dt_total_microseconds` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_microseconds__impl, `self`))
  }
}

`PlRExpr_dt_total_nanoseconds` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_total_nanoseconds__impl, `self`))
  }
}

`PlRExpr_dt_offset_by` <- function(self) {
  function(`by`) {
    `by` <- .savvy_extract_ptr(`by`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_offset_by__impl, `self`, `by`))
  }
}

`PlRExpr_dt_is_leap_year` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_is_leap_year__impl, `self`))
  }
}

`PlRExpr_dt_dst_offset` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_dst_offset__impl, `self`))
  }
}

`PlRExpr_dt_base_utc_offset` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_base_utc_offset__impl, `self`))
  }
}

`PlRExpr_dt_month_start` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_month_start__impl, `self`))
  }
}

`PlRExpr_dt_month_end` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_month_end__impl, `self`))
  }
}

`PlRExpr_dt_century` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_century__impl, `self`))
  }
}

`PlRExpr_dt_add_business_days` <- function(self) {
  function(`n`, `week_mask`, `holidays`, `roll`) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_dt_add_business_days__impl, `self`, `n`, `week_mask`, `holidays`, `roll`))
  }
}

`PlRExpr_print` <- function(self) {
  function() {
    invisible(.Call(savvy_PlRExpr_print__impl, `self`))
  }
}

`PlRExpr_add` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_add__impl, `self`, `rhs`))
  }
}

`PlRExpr_sub` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_sub__impl, `self`, `rhs`))
  }
}

`PlRExpr_mul` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_mul__impl, `self`, `rhs`))
  }
}

`PlRExpr_div` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_div__impl, `self`, `rhs`))
  }
}

`PlRExpr_rem` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_rem__impl, `self`, `rhs`))
  }
}

`PlRExpr_floor_div` <- function(self) {
  function(`rhs`) {
    `rhs` <- .savvy_extract_ptr(`rhs`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_floor_div__impl, `self`, `rhs`))
  }
}

`PlRExpr_neg` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_neg__impl, `self`))
  }
}

`PlRExpr_eq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_eq__impl, `self`, `other`))
  }
}

`PlRExpr_eq_missing` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_eq_missing__impl, `self`, `other`))
  }
}

`PlRExpr_neq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_neq__impl, `self`, `other`))
  }
}

`PlRExpr_neq_missing` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_neq_missing__impl, `self`, `other`))
  }
}

`PlRExpr_gt` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_gt__impl, `self`, `other`))
  }
}

`PlRExpr_gt_eq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_gt_eq__impl, `self`, `other`))
  }
}

`PlRExpr_lt_eq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_lt_eq__impl, `self`, `other`))
  }
}

`PlRExpr_lt` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_lt__impl, `self`, `other`))
  }
}

`PlRExpr_alias` <- function(self) {
  function(`name`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_alias__impl, `self`, `name`))
  }
}

`PlRExpr_not` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_not__impl, `self`))
  }
}

`PlRExpr_is_null` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_null__impl, `self`))
  }
}

`PlRExpr_is_not_null` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_not_null__impl, `self`))
  }
}

`PlRExpr_is_infinite` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_infinite__impl, `self`))
  }
}

`PlRExpr_is_finite` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_finite__impl, `self`))
  }
}

`PlRExpr_is_nan` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_nan__impl, `self`))
  }
}

`PlRExpr_is_not_nan` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_is_not_nan__impl, `self`))
  }
}

`PlRExpr_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_min__impl, `self`))
  }
}

`PlRExpr_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_max__impl, `self`))
  }
}

`PlRExpr_nan_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_nan_max__impl, `self`))
  }
}

`PlRExpr_nan_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_nan_min__impl, `self`))
  }
}

`PlRExpr_mean` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_mean__impl, `self`))
  }
}

`PlRExpr_median` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_median__impl, `self`))
  }
}

`PlRExpr_sum` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_sum__impl, `self`))
  }
}

`PlRExpr_cast` <- function(self) {
  function(`dtype`, `strict`, `wrap_numerical`) {
    `dtype` <- .savvy_extract_ptr(`dtype`, "PlRDataType")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_cast__impl, `self`, `dtype`, `strict`, `wrap_numerical`))
  }
}

`PlRExpr_sort_with` <- function(self) {
  function(`descending`, `nulls_last`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_sort_with__impl, `self`, `descending`, `nulls_last`))
  }
}

`PlRExpr_arg_sort` <- function(self) {
  function(`descending`, `nulls_last`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_arg_sort__impl, `self`, `descending`, `nulls_last`))
  }
}

`PlRExpr_sort_by` <- function(self) {
  function(`by`, `descending`, `nulls_last`, `multithreaded`, `maintain_order`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_sort_by__impl, `self`, `by`, `descending`, `nulls_last`, `multithreaded`, `maintain_order`))
  }
}

`PlRExpr_first` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_first__impl, `self`))
  }
}

`PlRExpr_last` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_last__impl, `self`))
  }
}

`PlRExpr_filter` <- function(self) {
  function(`predicate`) {
    `predicate` <- .savvy_extract_ptr(`predicate`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_filter__impl, `self`, `predicate`))
  }
}

`PlRExpr_reverse` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_reverse__impl, `self`))
  }
}

`PlRExpr_slice` <- function(self) {
  function(`offset`, `length`) {
    `offset` <- .savvy_extract_ptr(`offset`, "PlRExpr")
    `length` <- .savvy_extract_ptr(`length`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_slice__impl, `self`, `offset`, `length`))
  }
}

`PlRExpr_over` <- function(self) {
  function(`partition_by`, `order_by_descending`, `order_by_nulls_last`, `mapping_strategy`, `order_by` = NULL) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_over__impl, `self`, `partition_by`, `order_by_descending`, `order_by_nulls_last`, `mapping_strategy`, `order_by`))
  }
}

`PlRExpr_and` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_and__impl, `self`, `other`))
  }
}

`PlRExpr_or` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_or__impl, `self`, `other`))
  }
}

`PlRExpr_xor` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_xor__impl, `self`, `other`))
  }
}

`PlRExpr_pow` <- function(self) {
  function(`exponent`) {
    `exponent` <- .savvy_extract_ptr(`exponent`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_pow__impl, `self`, `exponent`))
  }
}

`PlRExpr_diff` <- function(self) {
  function(`n`, `null_behavior`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_diff__impl, `self`, `n`, `null_behavior`))
  }
}

`PlRExpr_reshape` <- function(self) {
  function(`dimensions`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_reshape__impl, `self`, `dimensions`))
  }
}

`PlRExpr_any` <- function(self) {
  function(`ignore_nulls`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_any__impl, `self`, `ignore_nulls`))
  }
}

`PlRExpr_all` <- function(self) {
  function(`ignore_nulls`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_all__impl, `self`, `ignore_nulls`))
  }
}

`PlRExpr_map_batches` <- function(self) {
  function(`lambda`, `agg_list`, `output_type` = NULL) {
    `output_type` <- .savvy_extract_ptr(`output_type`, "PlRDataType")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_map_batches__impl, `self`, `lambda`, `agg_list`, `output_type`))
  }
}

`PlRExpr_explode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_explode__impl, `self`))
  }
}

`PlRExpr_list_len` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_len__impl, `self`))
  }
}

`PlRExpr_list_contains` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_contains__impl, `self`, `other`))
  }
}

`PlRExpr_list_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_max__impl, `self`))
  }
}

`PlRExpr_list_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_min__impl, `self`))
  }
}

`PlRExpr_list_sum` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_sum__impl, `self`))
  }
}

`PlRExpr_list_mean` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_mean__impl, `self`))
  }
}

`PlRExpr_list_sort` <- function(self) {
  function(`descending`, `nulls_last`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_sort__impl, `self`, `descending`, `nulls_last`))
  }
}

`PlRExpr_list_reverse` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_reverse__impl, `self`))
  }
}

`PlRExpr_list_unique` <- function(self) {
  function(`maintain_order`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_unique__impl, `self`, `maintain_order`))
  }
}

`PlRExpr_list_n_unique` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_n_unique__impl, `self`))
  }
}

`PlRExpr_list_gather` <- function(self) {
  function(`index`, `null_on_oob`) {
    `index` <- .savvy_extract_ptr(`index`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_gather__impl, `self`, `index`, `null_on_oob`))
  }
}

`PlRExpr_list_gather_every` <- function(self) {
  function(`n`, `offset`) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    `offset` <- .savvy_extract_ptr(`offset`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_gather_every__impl, `self`, `n`, `offset`))
  }
}

`PlRExpr_list_get` <- function(self) {
  function(`index`, `null_on_oob`) {
    `index` <- .savvy_extract_ptr(`index`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_get__impl, `self`, `index`, `null_on_oob`))
  }
}

`PlRExpr_list_join` <- function(self) {
  function(`separator`, `ignore_nulls`) {
    `separator` <- .savvy_extract_ptr(`separator`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_join__impl, `self`, `separator`, `ignore_nulls`))
  }
}

`PlRExpr_list_arg_min` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_arg_min__impl, `self`))
  }
}

`PlRExpr_list_arg_max` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_arg_max__impl, `self`))
  }
}

`PlRExpr_list_diff` <- function(self) {
  function(`n`, `null_behavior`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_diff__impl, `self`, `n`, `null_behavior`))
  }
}

`PlRExpr_list_shift` <- function(self) {
  function(`periods`) {
    `periods` <- .savvy_extract_ptr(`periods`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_shift__impl, `self`, `periods`))
  }
}

`PlRExpr_list_slice` <- function(self) {
  function(`offset`, `length` = NULL) {
    `offset` <- .savvy_extract_ptr(`offset`, "PlRExpr")
    `length` <- .savvy_extract_ptr(`length`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_slice__impl, `self`, `offset`, `length`))
  }
}

`PlRExpr_list_eval` <- function(self) {
  function(`expr`, `parallel`) {
    `expr` <- .savvy_extract_ptr(`expr`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_eval__impl, `self`, `expr`, `parallel`))
  }
}

`PlRExpr_list_all` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_all__impl, `self`))
  }
}

`PlRExpr_list_any` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_any__impl, `self`))
  }
}

`PlRExpr_list_set_operation` <- function(self) {
  function(`other`, `operation`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_set_operation__impl, `self`, `other`, `operation`))
  }
}

`PlRExpr_list_sample_n` <- function(self) {
  function(`n`, `with_replacement`, `shuffle`, `seed` = NULL) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_sample_n__impl, `self`, `n`, `with_replacement`, `shuffle`, `seed`))
  }
}

`PlRExpr_list_sample_frac` <- function(self) {
  function(`frac`, `with_replacement`, `shuffle`, `seed` = NULL) {
    `frac` <- .savvy_extract_ptr(`frac`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_sample_frac__impl, `self`, `frac`, `with_replacement`, `shuffle`, `seed`))
  }
}

`PlRExpr_list_median` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_median__impl, `self`))
  }
}

`PlRExpr_list_std` <- function(self) {
  function(`ddof`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_std__impl, `self`, `ddof`))
  }
}

`PlRExpr_list_var` <- function(self) {
  function(`ddof`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_var__impl, `self`, `ddof`))
  }
}

`PlRExpr_list_to_array` <- function(self) {
  function(`width`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_to_array__impl, `self`, `width`))
  }
}

`PlRExpr_list_drop_nulls` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_drop_nulls__impl, `self`))
  }
}

`PlRExpr_list_count_matches` <- function(self) {
  function(`expr`) {
    `expr` <- .savvy_extract_ptr(`expr`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_list_count_matches__impl, `self`, `expr`))
  }
}

`PlRExpr_meta_eq` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .Call(savvy_PlRExpr_meta_eq__impl, `self`, `other`)
  }
}

`PlRExpr_meta_pop` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_pop__impl, `self`)
  }
}

`PlRExpr_meta_root_names` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_root_names__impl, `self`)
  }
}

`PlRExpr_meta_output_name` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_output_name__impl, `self`)
  }
}

`PlRExpr_meta_undo_aliases` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_meta_undo_aliases__impl, `self`))
  }
}

`PlRExpr_meta_has_multiple_outputs` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_has_multiple_outputs__impl, `self`)
  }
}

`PlRExpr_meta_is_regex_projection` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_is_regex_projection__impl, `self`)
  }
}

`PlRExpr_meta_is_column_selection` <- function(self) {
  function(`allow_aliasing`) {
    .Call(savvy_PlRExpr_meta_is_column_selection__impl, `self`, `allow_aliasing`)
  }
}

`PlRExpr__meta_selector_add` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr__meta_selector_add__impl, `self`, `other`))
  }
}

`PlRExpr__meta_selector_and` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr__meta_selector_and__impl, `self`, `other`))
  }
}

`PlRExpr__meta_selector_sub` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr__meta_selector_sub__impl, `self`, `other`))
  }
}

`PlRExpr__meta_as_selector` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr__meta_as_selector__impl, `self`))
  }
}

`PlRExpr_compute_tree_format` <- function(self) {
  function(`display_as_dot`) {
    .Call(savvy_PlRExpr_compute_tree_format__impl, `self`, `display_as_dot`)
  }
}

`PlRExpr_meta_is_column` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_meta_is_column__impl, `self`)
  }
}

`PlRExpr_name_keep` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_keep__impl, `self`))
  }
}

`PlRExpr_name_prefix` <- function(self) {
  function(`prefix`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_prefix__impl, `self`, `prefix`))
  }
}

`PlRExpr_name_suffix` <- function(self) {
  function(`suffix`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_suffix__impl, `self`, `suffix`))
  }
}

`PlRExpr_name_to_lowercase` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_to_lowercase__impl, `self`))
  }
}

`PlRExpr_name_to_uppercase` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_to_uppercase__impl, `self`))
  }
}

`PlRExpr_name_prefix_fields` <- function(self) {
  function(`prefix`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_prefix_fields__impl, `self`, `prefix`))
  }
}

`PlRExpr_name_suffix_fields` <- function(self) {
  function(`suffix`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_name_suffix_fields__impl, `self`, `suffix`))
  }
}

`PlRExpr_serialize_binary` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_serialize_binary__impl, `self`)
  }
}

`PlRExpr_serialize_json` <- function(self) {
  function() {
    .Call(savvy_PlRExpr_serialize_json__impl, `self`)
  }
}

`PlRExpr_str_len_bytes` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_len_bytes__impl, `self`))
  }
}

`PlRExpr_str_len_chars` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_len_chars__impl, `self`))
  }
}

`PlRExpr_str_join` <- function(self) {
  function(`delimiter`, `ignore_nulls`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_join__impl, `self`, `delimiter`, `ignore_nulls`))
  }
}

`PlRExpr_str_to_uppercase` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_uppercase__impl, `self`))
  }
}

`PlRExpr_str_to_lowercase` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_lowercase__impl, `self`))
  }
}

`PlRExpr_str_strip_chars` <- function(self) {
  function(`matches`) {
    `matches` <- .savvy_extract_ptr(`matches`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_strip_chars__impl, `self`, `matches`))
  }
}

`PlRExpr_str_strip_chars_end` <- function(self) {
  function(`matches`) {
    `matches` <- .savvy_extract_ptr(`matches`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_strip_chars_end__impl, `self`, `matches`))
  }
}

`PlRExpr_str_strip_chars_start` <- function(self) {
  function(`matches`) {
    `matches` <- .savvy_extract_ptr(`matches`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_strip_chars_start__impl, `self`, `matches`))
  }
}

`PlRExpr_str_zfill` <- function(self) {
  function(`alignment`) {
    `alignment` <- .savvy_extract_ptr(`alignment`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_zfill__impl, `self`, `alignment`))
  }
}

`PlRExpr_str_pad_end` <- function(self) {
  function(`width`, `fillchar`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_pad_end__impl, `self`, `width`, `fillchar`))
  }
}

`PlRExpr_str_pad_start` <- function(self) {
  function(`width`, `fillchar`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_pad_start__impl, `self`, `width`, `fillchar`))
  }
}

`PlRExpr_str_contains` <- function(self) {
  function(`pat`, `literal`, `strict`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_contains__impl, `self`, `pat`, `literal`, `strict`))
  }
}

`PlRExpr_str_ends_with` <- function(self) {
  function(`sub`) {
    `sub` <- .savvy_extract_ptr(`sub`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_ends_with__impl, `self`, `sub`))
  }
}

`PlRExpr_str_starts_with` <- function(self) {
  function(`sub`) {
    `sub` <- .savvy_extract_ptr(`sub`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_starts_with__impl, `self`, `sub`))
  }
}

`PlRExpr_str_json_path_match` <- function(self) {
  function(`pat`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_json_path_match__impl, `self`, `pat`))
  }
}

`PlRExpr_str_hex_encode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_hex_encode__impl, `self`))
  }
}

`PlRExpr_str_hex_decode` <- function(self) {
  function(`strict`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_hex_decode__impl, `self`, `strict`))
  }
}

`PlRExpr_str_base64_encode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_base64_encode__impl, `self`))
  }
}

`PlRExpr_str_base64_decode` <- function(self) {
  function(`strict`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_base64_decode__impl, `self`, `strict`))
  }
}

`PlRExpr_str_extract` <- function(self) {
  function(`pattern`, `group_index`) {
    `pattern` <- .savvy_extract_ptr(`pattern`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_extract__impl, `self`, `pattern`, `group_index`))
  }
}

`PlRExpr_str_extract_all` <- function(self) {
  function(`pattern`) {
    `pattern` <- .savvy_extract_ptr(`pattern`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_extract_all__impl, `self`, `pattern`))
  }
}

`PlRExpr_str_extract_groups` <- function(self) {
  function(`pattern`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_extract_groups__impl, `self`, `pattern`))
  }
}

`PlRExpr_str_count_matches` <- function(self) {
  function(`pat`, `literal`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_count_matches__impl, `self`, `pat`, `literal`))
  }
}

`PlRExpr_str_to_date` <- function(self) {
  function(`strict`, `exact`, `cache`, `format` = NULL) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_date__impl, `self`, `strict`, `exact`, `cache`, `format`))
  }
}

`PlRExpr_str_to_datetime` <- function(self) {
  function(`strict`, `exact`, `cache`, `ambiguous`, `format` = NULL, `time_unit` = NULL, `time_zone` = NULL) {
    `ambiguous` <- .savvy_extract_ptr(`ambiguous`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_datetime__impl, `self`, `strict`, `exact`, `cache`, `ambiguous`, `format`, `time_unit`, `time_zone`))
  }
}

`PlRExpr_str_to_time` <- function(self) {
  function(`strict`, `cache`, `format` = NULL) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_time__impl, `self`, `strict`, `cache`, `format`))
  }
}

`PlRExpr_str_split` <- function(self) {
  function(`by`, `inclusive`) {
    `by` <- .savvy_extract_ptr(`by`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_split__impl, `self`, `by`, `inclusive`))
  }
}

`PlRExpr_str_split_exact` <- function(self) {
  function(`by`, `n`, `inclusive`) {
    `by` <- .savvy_extract_ptr(`by`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_split_exact__impl, `self`, `by`, `n`, `inclusive`))
  }
}

`PlRExpr_str_splitn` <- function(self) {
  function(`by`, `n`) {
    `by` <- .savvy_extract_ptr(`by`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_splitn__impl, `self`, `by`, `n`))
  }
}

`PlRExpr_str_replace` <- function(self) {
  function(`pat`, `value`, `literal`, `n`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    `value` <- .savvy_extract_ptr(`value`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_replace__impl, `self`, `pat`, `value`, `literal`, `n`))
  }
}

`PlRExpr_str_replace_all` <- function(self) {
  function(`pat`, `value`, `literal`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    `value` <- .savvy_extract_ptr(`value`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_replace_all__impl, `self`, `pat`, `value`, `literal`))
  }
}

`PlRExpr_str_slice` <- function(self) {
  function(`offset`, `length`) {
    `offset` <- .savvy_extract_ptr(`offset`, "PlRExpr")
    `length` <- .savvy_extract_ptr(`length`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_slice__impl, `self`, `offset`, `length`))
  }
}

`PlRExpr_str_to_integer` <- function(self) {
  function(`base`, `strict`) {
    `base` <- .savvy_extract_ptr(`base`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_to_integer__impl, `self`, `base`, `strict`))
  }
}

`PlRExpr_str_reverse` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_reverse__impl, `self`))
  }
}

`PlRExpr_str_contains_any` <- function(self) {
  function(`patterns`, `ascii_case_insensitive`) {
    `patterns` <- .savvy_extract_ptr(`patterns`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_contains_any__impl, `self`, `patterns`, `ascii_case_insensitive`))
  }
}

`PlRExpr_str_replace_many` <- function(self) {
  function(`patterns`, `replace_with`, `ascii_case_insensitive`) {
    `patterns` <- .savvy_extract_ptr(`patterns`, "PlRExpr")
    `replace_with` <- .savvy_extract_ptr(`replace_with`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_replace_many__impl, `self`, `patterns`, `replace_with`, `ascii_case_insensitive`))
  }
}

`PlRExpr_str_extract_many` <- function(self) {
  function(`patterns`, `ascii_case_insensitive`, `overlapping`) {
    `patterns` <- .savvy_extract_ptr(`patterns`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_extract_many__impl, `self`, `patterns`, `ascii_case_insensitive`, `overlapping`))
  }
}

`PlRExpr_str_find` <- function(self) {
  function(`pat`, `literal`, `strict`) {
    `pat` <- .savvy_extract_ptr(`pat`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_find__impl, `self`, `pat`, `literal`, `strict`))
  }
}

`PlRExpr_str_head` <- function(self) {
  function(`n`) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_head__impl, `self`, `n`))
  }
}

`PlRExpr_str_tail` <- function(self) {
  function(`n`) {
    `n` <- .savvy_extract_ptr(`n`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_str_tail__impl, `self`, `n`))
  }
}

`PlRExpr_struct_field_by_index` <- function(self) {
  function(`index`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_struct_field_by_index__impl, `self`, `index`))
  }
}

`PlRExpr_struct_multiple_fields` <- function(self) {
  function(`names`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_struct_multiple_fields__impl, `self`, `names`))
  }
}

`PlRExpr_struct_rename_fields` <- function(self) {
  function(`names`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_struct_rename_fields__impl, `self`, `names`))
  }
}

`PlRExpr_struct_json_encode` <- function(self) {
  function() {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_struct_json_encode__impl, `self`))
  }
}

`PlRExpr_struct_with_fields` <- function(self) {
  function(`fields`) {
    .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_struct_with_fields__impl, `self`, `fields`))
  }
}

`.savvy_wrap_PlRExpr` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`arr_max` <- `PlRExpr_arr_max`(ptr)
  e$`arr_min` <- `PlRExpr_arr_min`(ptr)
  e$`arr_sum` <- `PlRExpr_arr_sum`(ptr)
  e$`arr_std` <- `PlRExpr_arr_std`(ptr)
  e$`arr_var` <- `PlRExpr_arr_var`(ptr)
  e$`arr_median` <- `PlRExpr_arr_median`(ptr)
  e$`arr_unique` <- `PlRExpr_arr_unique`(ptr)
  e$`arr_to_list` <- `PlRExpr_arr_to_list`(ptr)
  e$`arr_all` <- `PlRExpr_arr_all`(ptr)
  e$`arr_any` <- `PlRExpr_arr_any`(ptr)
  e$`arr_sort` <- `PlRExpr_arr_sort`(ptr)
  e$`arr_reverse` <- `PlRExpr_arr_reverse`(ptr)
  e$`arr_arg_min` <- `PlRExpr_arr_arg_min`(ptr)
  e$`arr_arg_max` <- `PlRExpr_arr_arg_max`(ptr)
  e$`arr_get` <- `PlRExpr_arr_get`(ptr)
  e$`arr_join` <- `PlRExpr_arr_join`(ptr)
  e$`arr_contains` <- `PlRExpr_arr_contains`(ptr)
  e$`arr_count_matches` <- `PlRExpr_arr_count_matches`(ptr)
  e$`arr_shift` <- `PlRExpr_arr_shift`(ptr)
  e$`arr_n_unique` <- `PlRExpr_arr_n_unique`(ptr)
  e$`bin_contains` <- `PlRExpr_bin_contains`(ptr)
  e$`bin_ends_with` <- `PlRExpr_bin_ends_with`(ptr)
  e$`bin_starts_with` <- `PlRExpr_bin_starts_with`(ptr)
  e$`bin_hex_decode` <- `PlRExpr_bin_hex_decode`(ptr)
  e$`bin_base64_decode` <- `PlRExpr_bin_base64_decode`(ptr)
  e$`bin_hex_encode` <- `PlRExpr_bin_hex_encode`(ptr)
  e$`bin_base64_encode` <- `PlRExpr_bin_base64_encode`(ptr)
  e$`bin_size_bytes` <- `PlRExpr_bin_size_bytes`(ptr)
  e$`cat_get_categories` <- `PlRExpr_cat_get_categories`(ptr)
  e$`cat_set_ordering` <- `PlRExpr_cat_set_ordering`(ptr)
  e$`dt_convert_time_zone` <- `PlRExpr_dt_convert_time_zone`(ptr)
  e$`dt_replace_time_zone` <- `PlRExpr_dt_replace_time_zone`(ptr)
  e$`dt_truncate` <- `PlRExpr_dt_truncate`(ptr)
  e$`dt_round` <- `PlRExpr_dt_round`(ptr)
  e$`dt_time` <- `PlRExpr_dt_time`(ptr)
  e$`dt_date` <- `PlRExpr_dt_date`(ptr)
  e$`dt_combine` <- `PlRExpr_dt_combine`(ptr)
  e$`dt_to_string` <- `PlRExpr_dt_to_string`(ptr)
  e$`dt_year` <- `PlRExpr_dt_year`(ptr)
  e$`dt_iso_year` <- `PlRExpr_dt_iso_year`(ptr)
  e$`dt_quarter` <- `PlRExpr_dt_quarter`(ptr)
  e$`dt_month` <- `PlRExpr_dt_month`(ptr)
  e$`dt_week` <- `PlRExpr_dt_week`(ptr)
  e$`dt_weekday` <- `PlRExpr_dt_weekday`(ptr)
  e$`dt_day` <- `PlRExpr_dt_day`(ptr)
  e$`dt_ordinal_day` <- `PlRExpr_dt_ordinal_day`(ptr)
  e$`dt_hour` <- `PlRExpr_dt_hour`(ptr)
  e$`dt_minute` <- `PlRExpr_dt_minute`(ptr)
  e$`dt_second` <- `PlRExpr_dt_second`(ptr)
  e$`dt_millisecond` <- `PlRExpr_dt_millisecond`(ptr)
  e$`dt_microsecond` <- `PlRExpr_dt_microsecond`(ptr)
  e$`dt_nanosecond` <- `PlRExpr_dt_nanosecond`(ptr)
  e$`dt_timestamp` <- `PlRExpr_dt_timestamp`(ptr)
  e$`dt_epoch_seconds` <- `PlRExpr_dt_epoch_seconds`(ptr)
  e$`dt_with_time_unit` <- `PlRExpr_dt_with_time_unit`(ptr)
  e$`dt_cast_time_unit` <- `PlRExpr_dt_cast_time_unit`(ptr)
  e$`dt_total_days` <- `PlRExpr_dt_total_days`(ptr)
  e$`dt_total_hours` <- `PlRExpr_dt_total_hours`(ptr)
  e$`dt_total_minutes` <- `PlRExpr_dt_total_minutes`(ptr)
  e$`dt_total_seconds` <- `PlRExpr_dt_total_seconds`(ptr)
  e$`dt_total_milliseconds` <- `PlRExpr_dt_total_milliseconds`(ptr)
  e$`dt_total_microseconds` <- `PlRExpr_dt_total_microseconds`(ptr)
  e$`dt_total_nanoseconds` <- `PlRExpr_dt_total_nanoseconds`(ptr)
  e$`dt_offset_by` <- `PlRExpr_dt_offset_by`(ptr)
  e$`dt_is_leap_year` <- `PlRExpr_dt_is_leap_year`(ptr)
  e$`dt_dst_offset` <- `PlRExpr_dt_dst_offset`(ptr)
  e$`dt_base_utc_offset` <- `PlRExpr_dt_base_utc_offset`(ptr)
  e$`dt_month_start` <- `PlRExpr_dt_month_start`(ptr)
  e$`dt_month_end` <- `PlRExpr_dt_month_end`(ptr)
  e$`dt_century` <- `PlRExpr_dt_century`(ptr)
  e$`dt_add_business_days` <- `PlRExpr_dt_add_business_days`(ptr)
  e$`print` <- `PlRExpr_print`(ptr)
  e$`add` <- `PlRExpr_add`(ptr)
  e$`sub` <- `PlRExpr_sub`(ptr)
  e$`mul` <- `PlRExpr_mul`(ptr)
  e$`div` <- `PlRExpr_div`(ptr)
  e$`rem` <- `PlRExpr_rem`(ptr)
  e$`floor_div` <- `PlRExpr_floor_div`(ptr)
  e$`neg` <- `PlRExpr_neg`(ptr)
  e$`eq` <- `PlRExpr_eq`(ptr)
  e$`eq_missing` <- `PlRExpr_eq_missing`(ptr)
  e$`neq` <- `PlRExpr_neq`(ptr)
  e$`neq_missing` <- `PlRExpr_neq_missing`(ptr)
  e$`gt` <- `PlRExpr_gt`(ptr)
  e$`gt_eq` <- `PlRExpr_gt_eq`(ptr)
  e$`lt_eq` <- `PlRExpr_lt_eq`(ptr)
  e$`lt` <- `PlRExpr_lt`(ptr)
  e$`alias` <- `PlRExpr_alias`(ptr)
  e$`not` <- `PlRExpr_not`(ptr)
  e$`is_null` <- `PlRExpr_is_null`(ptr)
  e$`is_not_null` <- `PlRExpr_is_not_null`(ptr)
  e$`is_infinite` <- `PlRExpr_is_infinite`(ptr)
  e$`is_finite` <- `PlRExpr_is_finite`(ptr)
  e$`is_nan` <- `PlRExpr_is_nan`(ptr)
  e$`is_not_nan` <- `PlRExpr_is_not_nan`(ptr)
  e$`min` <- `PlRExpr_min`(ptr)
  e$`max` <- `PlRExpr_max`(ptr)
  e$`nan_max` <- `PlRExpr_nan_max`(ptr)
  e$`nan_min` <- `PlRExpr_nan_min`(ptr)
  e$`mean` <- `PlRExpr_mean`(ptr)
  e$`median` <- `PlRExpr_median`(ptr)
  e$`sum` <- `PlRExpr_sum`(ptr)
  e$`cast` <- `PlRExpr_cast`(ptr)
  e$`sort_with` <- `PlRExpr_sort_with`(ptr)
  e$`arg_sort` <- `PlRExpr_arg_sort`(ptr)
  e$`sort_by` <- `PlRExpr_sort_by`(ptr)
  e$`first` <- `PlRExpr_first`(ptr)
  e$`last` <- `PlRExpr_last`(ptr)
  e$`filter` <- `PlRExpr_filter`(ptr)
  e$`reverse` <- `PlRExpr_reverse`(ptr)
  e$`slice` <- `PlRExpr_slice`(ptr)
  e$`over` <- `PlRExpr_over`(ptr)
  e$`and` <- `PlRExpr_and`(ptr)
  e$`or` <- `PlRExpr_or`(ptr)
  e$`xor` <- `PlRExpr_xor`(ptr)
  e$`pow` <- `PlRExpr_pow`(ptr)
  e$`diff` <- `PlRExpr_diff`(ptr)
  e$`reshape` <- `PlRExpr_reshape`(ptr)
  e$`any` <- `PlRExpr_any`(ptr)
  e$`all` <- `PlRExpr_all`(ptr)
  e$`map_batches` <- `PlRExpr_map_batches`(ptr)
  e$`explode` <- `PlRExpr_explode`(ptr)
  e$`list_len` <- `PlRExpr_list_len`(ptr)
  e$`list_contains` <- `PlRExpr_list_contains`(ptr)
  e$`list_max` <- `PlRExpr_list_max`(ptr)
  e$`list_min` <- `PlRExpr_list_min`(ptr)
  e$`list_sum` <- `PlRExpr_list_sum`(ptr)
  e$`list_mean` <- `PlRExpr_list_mean`(ptr)
  e$`list_sort` <- `PlRExpr_list_sort`(ptr)
  e$`list_reverse` <- `PlRExpr_list_reverse`(ptr)
  e$`list_unique` <- `PlRExpr_list_unique`(ptr)
  e$`list_n_unique` <- `PlRExpr_list_n_unique`(ptr)
  e$`list_gather` <- `PlRExpr_list_gather`(ptr)
  e$`list_gather_every` <- `PlRExpr_list_gather_every`(ptr)
  e$`list_get` <- `PlRExpr_list_get`(ptr)
  e$`list_join` <- `PlRExpr_list_join`(ptr)
  e$`list_arg_min` <- `PlRExpr_list_arg_min`(ptr)
  e$`list_arg_max` <- `PlRExpr_list_arg_max`(ptr)
  e$`list_diff` <- `PlRExpr_list_diff`(ptr)
  e$`list_shift` <- `PlRExpr_list_shift`(ptr)
  e$`list_slice` <- `PlRExpr_list_slice`(ptr)
  e$`list_eval` <- `PlRExpr_list_eval`(ptr)
  e$`list_all` <- `PlRExpr_list_all`(ptr)
  e$`list_any` <- `PlRExpr_list_any`(ptr)
  e$`list_set_operation` <- `PlRExpr_list_set_operation`(ptr)
  e$`list_sample_n` <- `PlRExpr_list_sample_n`(ptr)
  e$`list_sample_frac` <- `PlRExpr_list_sample_frac`(ptr)
  e$`list_median` <- `PlRExpr_list_median`(ptr)
  e$`list_std` <- `PlRExpr_list_std`(ptr)
  e$`list_var` <- `PlRExpr_list_var`(ptr)
  e$`list_to_array` <- `PlRExpr_list_to_array`(ptr)
  e$`list_drop_nulls` <- `PlRExpr_list_drop_nulls`(ptr)
  e$`list_count_matches` <- `PlRExpr_list_count_matches`(ptr)
  e$`meta_eq` <- `PlRExpr_meta_eq`(ptr)
  e$`meta_pop` <- `PlRExpr_meta_pop`(ptr)
  e$`meta_root_names` <- `PlRExpr_meta_root_names`(ptr)
  e$`meta_output_name` <- `PlRExpr_meta_output_name`(ptr)
  e$`meta_undo_aliases` <- `PlRExpr_meta_undo_aliases`(ptr)
  e$`meta_has_multiple_outputs` <- `PlRExpr_meta_has_multiple_outputs`(ptr)
  e$`meta_is_regex_projection` <- `PlRExpr_meta_is_regex_projection`(ptr)
  e$`meta_is_column_selection` <- `PlRExpr_meta_is_column_selection`(ptr)
  e$`_meta_selector_add` <- `PlRExpr__meta_selector_add`(ptr)
  e$`_meta_selector_and` <- `PlRExpr__meta_selector_and`(ptr)
  e$`_meta_selector_sub` <- `PlRExpr__meta_selector_sub`(ptr)
  e$`_meta_as_selector` <- `PlRExpr__meta_as_selector`(ptr)
  e$`compute_tree_format` <- `PlRExpr_compute_tree_format`(ptr)
  e$`meta_is_column` <- `PlRExpr_meta_is_column`(ptr)
  e$`name_keep` <- `PlRExpr_name_keep`(ptr)
  e$`name_prefix` <- `PlRExpr_name_prefix`(ptr)
  e$`name_suffix` <- `PlRExpr_name_suffix`(ptr)
  e$`name_to_lowercase` <- `PlRExpr_name_to_lowercase`(ptr)
  e$`name_to_uppercase` <- `PlRExpr_name_to_uppercase`(ptr)
  e$`name_prefix_fields` <- `PlRExpr_name_prefix_fields`(ptr)
  e$`name_suffix_fields` <- `PlRExpr_name_suffix_fields`(ptr)
  e$`serialize_binary` <- `PlRExpr_serialize_binary`(ptr)
  e$`serialize_json` <- `PlRExpr_serialize_json`(ptr)
  e$`str_len_bytes` <- `PlRExpr_str_len_bytes`(ptr)
  e$`str_len_chars` <- `PlRExpr_str_len_chars`(ptr)
  e$`str_join` <- `PlRExpr_str_join`(ptr)
  e$`str_to_uppercase` <- `PlRExpr_str_to_uppercase`(ptr)
  e$`str_to_lowercase` <- `PlRExpr_str_to_lowercase`(ptr)
  e$`str_strip_chars` <- `PlRExpr_str_strip_chars`(ptr)
  e$`str_strip_chars_end` <- `PlRExpr_str_strip_chars_end`(ptr)
  e$`str_strip_chars_start` <- `PlRExpr_str_strip_chars_start`(ptr)
  e$`str_zfill` <- `PlRExpr_str_zfill`(ptr)
  e$`str_pad_end` <- `PlRExpr_str_pad_end`(ptr)
  e$`str_pad_start` <- `PlRExpr_str_pad_start`(ptr)
  e$`str_contains` <- `PlRExpr_str_contains`(ptr)
  e$`str_ends_with` <- `PlRExpr_str_ends_with`(ptr)
  e$`str_starts_with` <- `PlRExpr_str_starts_with`(ptr)
  e$`str_json_path_match` <- `PlRExpr_str_json_path_match`(ptr)
  e$`str_hex_encode` <- `PlRExpr_str_hex_encode`(ptr)
  e$`str_hex_decode` <- `PlRExpr_str_hex_decode`(ptr)
  e$`str_base64_encode` <- `PlRExpr_str_base64_encode`(ptr)
  e$`str_base64_decode` <- `PlRExpr_str_base64_decode`(ptr)
  e$`str_extract` <- `PlRExpr_str_extract`(ptr)
  e$`str_extract_all` <- `PlRExpr_str_extract_all`(ptr)
  e$`str_extract_groups` <- `PlRExpr_str_extract_groups`(ptr)
  e$`str_count_matches` <- `PlRExpr_str_count_matches`(ptr)
  e$`str_to_date` <- `PlRExpr_str_to_date`(ptr)
  e$`str_to_datetime` <- `PlRExpr_str_to_datetime`(ptr)
  e$`str_to_time` <- `PlRExpr_str_to_time`(ptr)
  e$`str_split` <- `PlRExpr_str_split`(ptr)
  e$`str_split_exact` <- `PlRExpr_str_split_exact`(ptr)
  e$`str_splitn` <- `PlRExpr_str_splitn`(ptr)
  e$`str_replace` <- `PlRExpr_str_replace`(ptr)
  e$`str_replace_all` <- `PlRExpr_str_replace_all`(ptr)
  e$`str_slice` <- `PlRExpr_str_slice`(ptr)
  e$`str_to_integer` <- `PlRExpr_str_to_integer`(ptr)
  e$`str_reverse` <- `PlRExpr_str_reverse`(ptr)
  e$`str_contains_any` <- `PlRExpr_str_contains_any`(ptr)
  e$`str_replace_many` <- `PlRExpr_str_replace_many`(ptr)
  e$`str_extract_many` <- `PlRExpr_str_extract_many`(ptr)
  e$`str_find` <- `PlRExpr_str_find`(ptr)
  e$`str_head` <- `PlRExpr_str_head`(ptr)
  e$`str_tail` <- `PlRExpr_str_tail`(ptr)
  e$`struct_field_by_index` <- `PlRExpr_struct_field_by_index`(ptr)
  e$`struct_multiple_fields` <- `PlRExpr_struct_multiple_fields`(ptr)
  e$`struct_rename_fields` <- `PlRExpr_struct_rename_fields`(ptr)
  e$`struct_json_encode` <- `PlRExpr_struct_json_encode`(ptr)
  e$`struct_with_fields` <- `PlRExpr_struct_with_fields`(ptr)

  class(e) <- c("PlRExpr", "savvy_neopolars__sealed")
  e
}



`PlRExpr` <- new.env(parent = emptyenv())

### associated functions for PlRExpr

`PlRExpr`$`deserialize_binary` <- function(`data`) {
  .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_deserialize_binary__impl, `data`))
}

`PlRExpr`$`deserialize_json` <- function(`data`) {
  .savvy_wrap_PlRExpr(.Call(savvy_PlRExpr_deserialize_json__impl, `data`))
}


class(`PlRExpr`) <- c("PlRExpr__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRExpr__bundle` <- function(x, ...) {
  cat('PlRExpr')
}

### wrapper functions for PlRLazyFrame

`PlRLazyFrame_describe_plan` <- function(self) {
  function() {
    .Call(savvy_PlRLazyFrame_describe_plan__impl, `self`)
  }
}

`PlRLazyFrame_describe_optimized_plan` <- function(self) {
  function() {
    .Call(savvy_PlRLazyFrame_describe_optimized_plan__impl, `self`)
  }
}

`PlRLazyFrame_describe_plan_tree` <- function(self) {
  function() {
    .Call(savvy_PlRLazyFrame_describe_plan_tree__impl, `self`)
  }
}

`PlRLazyFrame_describe_optimized_plan_tree` <- function(self) {
  function() {
    .Call(savvy_PlRLazyFrame_describe_optimized_plan_tree__impl, `self`)
  }
}

`PlRLazyFrame_optimization_toggle` <- function(self) {
  function(`type_coercion`, `predicate_pushdown`, `projection_pushdown`, `simplify_expression`, `slice_pushdown`, `comm_subplan_elim`, `comm_subexpr_elim`, `cluster_with_columns`, `streaming`, `_eager`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_optimization_toggle__impl, `self`, `type_coercion`, `predicate_pushdown`, `projection_pushdown`, `simplify_expression`, `slice_pushdown`, `comm_subplan_elim`, `comm_subexpr_elim`, `cluster_with_columns`, `streaming`, `_eager`))
  }
}

`PlRLazyFrame_filter` <- function(self) {
  function(`predicate`) {
    `predicate` <- .savvy_extract_ptr(`predicate`, "PlRExpr")
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_filter__impl, `self`, `predicate`))
  }
}

`PlRLazyFrame_select` <- function(self) {
  function(`exprs`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_select__impl, `self`, `exprs`))
  }
}

`PlRLazyFrame_group_by` <- function(self) {
  function(`by`, `maintain_order`) {
    .savvy_wrap_PlRLazyGroupBy(.Call(savvy_PlRLazyFrame_group_by__impl, `self`, `by`, `maintain_order`))
  }
}

`PlRLazyFrame_collect` <- function(self) {
  function() {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRLazyFrame_collect__impl, `self`))
  }
}

`PlRLazyFrame_slice` <- function(self) {
  function(`offset`, `len` = NULL) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_slice__impl, `self`, `offset`, `len`))
  }
}

`PlRLazyFrame_tail` <- function(self) {
  function(`n`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_tail__impl, `self`, `n`))
  }
}

`PlRLazyFrame_drop` <- function(self) {
  function(`columns`, `strict`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_drop__impl, `self`, `columns`, `strict`))
  }
}

`PlRLazyFrame_cast` <- function(self) {
  function(`dtypes`, `strict`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_cast__impl, `self`, `dtypes`, `strict`))
  }
}

`PlRLazyFrame_cast_all` <- function(self) {
  function(`dtype`, `strict`) {
    `dtype` <- .savvy_extract_ptr(`dtype`, "PlRDataType")
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_cast_all__impl, `self`, `dtype`, `strict`))
  }
}

`PlRLazyFrame_collect_schema` <- function(self) {
  function() {
    .Call(savvy_PlRLazyFrame_collect_schema__impl, `self`)
  }
}

`PlRLazyFrame_sort_by_exprs` <- function(self) {
  function(`by`, `descending`, `nulls_last`, `maintain_order`, `multithreaded`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_sort_by_exprs__impl, `self`, `by`, `descending`, `nulls_last`, `maintain_order`, `multithreaded`))
  }
}

`PlRLazyFrame_with_columns` <- function(self) {
  function(`exprs`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_with_columns__impl, `self`, `exprs`))
  }
}

`.savvy_wrap_PlRLazyFrame` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`describe_plan` <- `PlRLazyFrame_describe_plan`(ptr)
  e$`describe_optimized_plan` <- `PlRLazyFrame_describe_optimized_plan`(ptr)
  e$`describe_plan_tree` <- `PlRLazyFrame_describe_plan_tree`(ptr)
  e$`describe_optimized_plan_tree` <- `PlRLazyFrame_describe_optimized_plan_tree`(ptr)
  e$`optimization_toggle` <- `PlRLazyFrame_optimization_toggle`(ptr)
  e$`filter` <- `PlRLazyFrame_filter`(ptr)
  e$`select` <- `PlRLazyFrame_select`(ptr)
  e$`group_by` <- `PlRLazyFrame_group_by`(ptr)
  e$`collect` <- `PlRLazyFrame_collect`(ptr)
  e$`slice` <- `PlRLazyFrame_slice`(ptr)
  e$`tail` <- `PlRLazyFrame_tail`(ptr)
  e$`drop` <- `PlRLazyFrame_drop`(ptr)
  e$`cast` <- `PlRLazyFrame_cast`(ptr)
  e$`cast_all` <- `PlRLazyFrame_cast_all`(ptr)
  e$`collect_schema` <- `PlRLazyFrame_collect_schema`(ptr)
  e$`sort_by_exprs` <- `PlRLazyFrame_sort_by_exprs`(ptr)
  e$`with_columns` <- `PlRLazyFrame_with_columns`(ptr)

  class(e) <- c("PlRLazyFrame", "savvy_neopolars__sealed")
  e
}



`PlRLazyFrame` <- new.env(parent = emptyenv())

### associated functions for PlRLazyFrame

`PlRLazyFrame`$`new_from_ipc` <- function(`source`, `cache`, `rechunk`, `try_parse_hive_dates`, `retries`, `row_index_offset`, `n_rows` = NULL, `row_index_name` = NULL, `storage_options` = NULL, `hive_partitioning` = NULL, `hive_schema` = NULL, `file_cache_ttl` = NULL, `include_file_paths` = NULL) {
  .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_new_from_ipc__impl, `source`, `cache`, `rechunk`, `try_parse_hive_dates`, `retries`, `row_index_offset`, `n_rows`, `row_index_name`, `storage_options`, `hive_partitioning`, `hive_schema`, `file_cache_ttl`, `include_file_paths`))
}

`PlRLazyFrame`$`new_from_parquet` <- function(`source`, `cache`, `parallel`, `rechunk`, `low_memory`, `use_statistics`, `try_parse_hive_dates`, `retries`, `glob`, `allow_missing_columns`, `row_index_offset`, `storage_options` = NULL, `n_rows` = NULL, `row_index_name` = NULL, `hive_partitioning` = NULL, `schema` = NULL, `hive_schema` = NULL, `include_file_paths` = NULL) {
  .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyFrame_new_from_parquet__impl, `source`, `cache`, `parallel`, `rechunk`, `low_memory`, `use_statistics`, `try_parse_hive_dates`, `retries`, `glob`, `allow_missing_columns`, `row_index_offset`, `storage_options`, `n_rows`, `row_index_name`, `hive_partitioning`, `schema`, `hive_schema`, `include_file_paths`))
}


class(`PlRLazyFrame`) <- c("PlRLazyFrame__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRLazyFrame__bundle` <- function(x, ...) {
  cat('PlRLazyFrame')
}

### wrapper functions for PlRLazyGroupBy

`PlRLazyGroupBy_agg` <- function(self) {
  function(`aggs`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyGroupBy_agg__impl, `self`, `aggs`))
  }
}

`PlRLazyGroupBy_head` <- function(self) {
  function(`n`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyGroupBy_head__impl, `self`, `n`))
  }
}

`PlRLazyGroupBy_tail` <- function(self) {
  function(`n`) {
    .savvy_wrap_PlRLazyFrame(.Call(savvy_PlRLazyGroupBy_tail__impl, `self`, `n`))
  }
}

`.savvy_wrap_PlRLazyGroupBy` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`agg` <- `PlRLazyGroupBy_agg`(ptr)
  e$`head` <- `PlRLazyGroupBy_head`(ptr)
  e$`tail` <- `PlRLazyGroupBy_tail`(ptr)

  class(e) <- c("PlRLazyGroupBy", "savvy_neopolars__sealed")
  e
}



`PlRLazyGroupBy` <- new.env(parent = emptyenv())

### associated functions for PlRLazyGroupBy



class(`PlRLazyGroupBy`) <- c("PlRLazyGroupBy__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRLazyGroupBy__bundle` <- function(x, ...) {
  cat('PlRLazyGroupBy')
}

### wrapper functions for PlRSeries

`PlRSeries_add` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_add__impl, `self`, `other`))
  }
}

`PlRSeries_sub` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_sub__impl, `self`, `other`))
  }
}

`PlRSeries_div` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_div__impl, `self`, `other`))
  }
}

`PlRSeries_mul` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_mul__impl, `self`, `other`))
  }
}

`PlRSeries_rem` <- function(self) {
  function(`other`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_rem__impl, `self`, `other`))
  }
}

`PlRSeries_to_r_vector` <- function(self) {
  function(`ensure_vector`, `int64`, `date`, `time`, `struct`, `decimal`, `as_clock_class`, `ambiguous`, `non_existent`, `local_time_zone`) {
    `ambiguous` <- .savvy_extract_ptr(`ambiguous`, "PlRExpr")
    .Call(savvy_PlRSeries_to_r_vector__impl, `self`, `ensure_vector`, `int64`, `date`, `time`, `struct`, `decimal`, `as_clock_class`, `ambiguous`, `non_existent`, `local_time_zone`)
  }
}

`PlRSeries_print` <- function(self) {
  function() {
    invisible(.Call(savvy_PlRSeries_print__impl, `self`))
  }
}

`PlRSeries_struct_unnest` <- function(self) {
  function() {
    .savvy_wrap_PlRDataFrame(.Call(savvy_PlRSeries_struct_unnest__impl, `self`))
  }
}

`PlRSeries_struct_fields` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_struct_fields__impl, `self`)
  }
}

`PlRSeries_cat_uses_lexical_ordering` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_cat_uses_lexical_ordering__impl, `self`)
  }
}

`PlRSeries_cat_is_local` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_cat_is_local__impl, `self`)
  }
}

`PlRSeries_cat_to_local` <- function(self) {
  function() {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_cat_to_local__impl, `self`))
  }
}

`PlRSeries_reshape` <- function(self) {
  function(`dimensions`) {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_reshape__impl, `self`, `dimensions`))
  }
}

`PlRSeries_clone` <- function(self) {
  function() {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_clone__impl, `self`))
  }
}

`PlRSeries_name` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_name__impl, `self`)
  }
}

`PlRSeries_rename` <- function(self) {
  function(`name`) {
    invisible(.Call(savvy_PlRSeries_rename__impl, `self`, `name`))
  }
}

`PlRSeries_dtype` <- function(self) {
  function() {
    .savvy_wrap_PlRDataType(.Call(savvy_PlRSeries_dtype__impl, `self`))
  }
}

`PlRSeries_equals` <- function(self) {
  function(`other`, `check_dtypes`, `check_names`, `null_equal`) {
    `other` <- .savvy_extract_ptr(`other`, "PlRSeries")
    .Call(savvy_PlRSeries_equals__impl, `self`, `other`, `check_dtypes`, `check_names`, `null_equal`)
  }
}

`PlRSeries_len` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_len__impl, `self`)
  }
}

`PlRSeries_cast` <- function(self) {
  function(`dtype`, `strict`) {
    `dtype` <- .savvy_extract_ptr(`dtype`, "PlRDataType")
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_cast__impl, `self`, `dtype`, `strict`))
  }
}

`PlRSeries_slice` <- function(self) {
  function(`offset`, `length` = NULL) {
    .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_slice__impl, `self`, `offset`, `length`))
  }
}

`PlRSeries_n_chunks` <- function(self) {
  function() {
    .Call(savvy_PlRSeries_n_chunks__impl, `self`)
  }
}

`.savvy_wrap_PlRSeries` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`add` <- `PlRSeries_add`(ptr)
  e$`sub` <- `PlRSeries_sub`(ptr)
  e$`div` <- `PlRSeries_div`(ptr)
  e$`mul` <- `PlRSeries_mul`(ptr)
  e$`rem` <- `PlRSeries_rem`(ptr)
  e$`to_r_vector` <- `PlRSeries_to_r_vector`(ptr)
  e$`print` <- `PlRSeries_print`(ptr)
  e$`struct_unnest` <- `PlRSeries_struct_unnest`(ptr)
  e$`struct_fields` <- `PlRSeries_struct_fields`(ptr)
  e$`cat_uses_lexical_ordering` <- `PlRSeries_cat_uses_lexical_ordering`(ptr)
  e$`cat_is_local` <- `PlRSeries_cat_is_local`(ptr)
  e$`cat_to_local` <- `PlRSeries_cat_to_local`(ptr)
  e$`reshape` <- `PlRSeries_reshape`(ptr)
  e$`clone` <- `PlRSeries_clone`(ptr)
  e$`name` <- `PlRSeries_name`(ptr)
  e$`rename` <- `PlRSeries_rename`(ptr)
  e$`dtype` <- `PlRSeries_dtype`(ptr)
  e$`equals` <- `PlRSeries_equals`(ptr)
  e$`len` <- `PlRSeries_len`(ptr)
  e$`cast` <- `PlRSeries_cast`(ptr)
  e$`slice` <- `PlRSeries_slice`(ptr)
  e$`n_chunks` <- `PlRSeries_n_chunks`(ptr)

  class(e) <- c("PlRSeries", "savvy_neopolars__sealed")
  e
}



`PlRSeries` <- new.env(parent = emptyenv())

### associated functions for PlRSeries

`PlRSeries`$`new_null` <- function(`name`, `length`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_null__impl, `name`, `length`))
}

`PlRSeries`$`new_f64` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_f64__impl, `name`, `values`))
}

`PlRSeries`$`new_i32` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i32__impl, `name`, `values`))
}

`PlRSeries`$`new_i64` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i64__impl, `name`, `values`))
}

`PlRSeries`$`new_bool` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_bool__impl, `name`, `values`))
}

`PlRSeries`$`new_str` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_str__impl, `name`, `values`))
}

`PlRSeries`$`new_single_binary` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_single_binary__impl, `name`, `values`))
}

`PlRSeries`$`new_binary` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_binary__impl, `name`, `values`))
}

`PlRSeries`$`new_series_list` <- function(`name`, `values`, `strict`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_series_list__impl, `name`, `values`, `strict`))
}

`PlRSeries`$`new_i32_from_date` <- function(`name`, `values`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i32_from_date__impl, `name`, `values`))
}

`PlRSeries`$`new_i64_from_numeric_and_multiplier` <- function(`name`, `values`, `multiplier`, `rounding`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i64_from_numeric_and_multiplier__impl, `name`, `values`, `multiplier`, `rounding`))
}

`PlRSeries`$`new_i64_from_clock_pair` <- function(`name`, `left`, `right`, `precision`) {
  .savvy_wrap_PlRSeries(.Call(savvy_PlRSeries_new_i64_from_clock_pair__impl, `name`, `left`, `right`, `precision`))
}


class(`PlRSeries`) <- c("PlRSeries__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRSeries__bundle` <- function(x, ...) {
  cat('PlRSeries')
}

### wrapper functions for PlRThen

`PlRThen_when` <- function(self) {
  function(`condition`) {
    `condition` <- .savvy_extract_ptr(`condition`, "PlRExpr")
    .savvy_wrap_PlRChainedWhen(.Call(savvy_PlRThen_when__impl, `self`, `condition`))
  }
}

`PlRThen_otherwise` <- function(self) {
  function(`statement`) {
    `statement` <- .savvy_extract_ptr(`statement`, "PlRExpr")
    .savvy_wrap_PlRExpr(.Call(savvy_PlRThen_otherwise__impl, `self`, `statement`))
  }
}

`.savvy_wrap_PlRThen` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`when` <- `PlRThen_when`(ptr)
  e$`otherwise` <- `PlRThen_otherwise`(ptr)

  class(e) <- c("PlRThen", "savvy_neopolars__sealed")
  e
}



`PlRThen` <- new.env(parent = emptyenv())

### associated functions for PlRThen



class(`PlRThen`) <- c("PlRThen__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRThen__bundle` <- function(x, ...) {
  cat('PlRThen')
}

### wrapper functions for PlRWhen

`PlRWhen_then` <- function(self) {
  function(`statement`) {
    `statement` <- .savvy_extract_ptr(`statement`, "PlRExpr")
    .savvy_wrap_PlRThen(.Call(savvy_PlRWhen_then__impl, `self`, `statement`))
  }
}

`.savvy_wrap_PlRWhen` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`then` <- `PlRWhen_then`(ptr)

  class(e) <- c("PlRWhen", "savvy_neopolars__sealed")
  e
}



`PlRWhen` <- new.env(parent = emptyenv())

### associated functions for PlRWhen



class(`PlRWhen`) <- c("PlRWhen__bundle", "savvy_neopolars__sealed")

#' @export
`print.PlRWhen__bundle` <- function(x, ...) {
  cat('PlRWhen')
}

