# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_minipolars_wrappers", use_symbols = TRUE, package_name = "minipolars")

#' @docType package
#' @usage NULL
#' @useDynLib minipolars, .registration = TRUE
NULL

new_csv_r <- function(path, sep, has_header, ignore_errors, skip_rows, n_rows, cache, overwrite_dtype) invisible(.Call(wrap__new_csv_r, path, sep, has_header, ignore_errors, skip_rows, n_rows, cache, overwrite_dtype))

Rdataframe <- new.env(parent = emptyenv())

Rdataframe$clone_extendr <- function() .Call(wrap__Rdataframe__clone_extendr, self)

Rdataframe$new <- function() .Call(wrap__Rdataframe__new)

Rdataframe$new_with_capacity <- function(capacity) .Call(wrap__Rdataframe__new_with_capacity, capacity)

Rdataframe$set_column_from_robj <- function(robj, name) .Call(wrap__Rdataframe__set_column_from_robj, self, robj, name)

Rdataframe$set_column_from_rseries <- function(x) .Call(wrap__Rdataframe__set_column_from_rseries, self, x)

Rdataframe$print <- function() invisible(.Call(wrap__Rdataframe__print, self))

Rdataframe$name <- function() .Call(wrap__Rdataframe__name, self)

Rdataframe$colnames <- function() .Call(wrap__Rdataframe__colnames, self)

Rdataframe$as_rlist_of_vectors <- function() .Call(wrap__Rdataframe__as_rlist_of_vectors, self)

Rdataframe$select <- function(exprs) .Call(wrap__Rdataframe__select, self, exprs)

#' @export
`$.Rdataframe` <- function (self, name) { func <- Rdataframe[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rdataframe` <- `$.Rdataframe`

Rexpr <- new.env(parent = emptyenv())

Rexpr$col <- function(name) .Call(wrap__Rexpr__col, name)

Rexpr$abs <- function() .Call(wrap__Rexpr__abs, self)

Rexpr$agg_groups <- function() .Call(wrap__Rexpr__agg_groups, self)

Rexpr$alias <- function(s) .Call(wrap__Rexpr__alias, self, s)

Rexpr$all <- function() .Call(wrap__Rexpr__all, self)

Rexpr$any <- function() .Call(wrap__Rexpr__any, self)

Rexpr$over <- function(vs) .Call(wrap__Rexpr__over, self, vs)

Rexpr$print <- function() invisible(.Call(wrap__Rexpr__print, self))

Rexpr$sum <- function() .Call(wrap__Rexpr__sum, self)

#' @export
`$.Rexpr` <- function (self, name) { func <- Rexpr[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rexpr` <- `$.Rexpr`

ProtoRexprArray <- new.env(parent = emptyenv())

ProtoRexprArray$new <- function() .Call(wrap__ProtoRexprArray__new)

ProtoRexprArray$push_back_str <- function(s) invisible(.Call(wrap__ProtoRexprArray__push_back_str, self, s))

ProtoRexprArray$push_back_rexpr <- function(r) invisible(.Call(wrap__ProtoRexprArray__push_back_rexpr, self, r))

ProtoRexprArray$pop_front_rexpr <- function(context) .Call(wrap__ProtoRexprArray__pop_front_rexpr, self, context)

ProtoRexprArray$print <- function() invisible(.Call(wrap__ProtoRexprArray__print, self))

ProtoRexprArray$add_context <- function(context) .Call(wrap__ProtoRexprArray__add_context, self, context)

#' @export
`$.ProtoRexprArray` <- function (self, name) { func <- ProtoRexprArray[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ProtoRexprArray` <- `$.ProtoRexprArray`

RexprArray <- new.env(parent = emptyenv())

RexprArray$print <- function() invisible(.Call(wrap__RexprArray__print, self))

#' @export
`$.RexprArray` <- function (self, name) { func <- RexprArray[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RexprArray` <- `$.RexprArray`

Rseries <- new.env(parent = emptyenv())

Rseries$new <- function(x, name) .Call(wrap__Rseries__new, x, name)

Rseries$rename <- function(name) invisible(.Call(wrap__Rseries__rename, self, name))

Rseries$name <- function() .Call(wrap__Rseries__name, self)

Rseries$print <- function() invisible(.Call(wrap__Rseries__print, self))

Rseries$cumsum <- function() invisible(.Call(wrap__Rseries__cumsum, self))

#' @export
`$.Rseries` <- function (self, name) { func <- Rseries[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rseries` <- `$.Rseries`

Rdatatype <- new.env(parent = emptyenv())

Rdatatype$new <- function(s) .Call(wrap__Rdatatype__new, s)

Rdatatype$print <- function() invisible(.Call(wrap__Rdatatype__print, self))

#' @export
`$.Rdatatype` <- function (self, name) { func <- Rdatatype[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rdatatype` <- `$.Rdatatype`

Rdatatype_vector <- new.env(parent = emptyenv())

Rdatatype_vector$new <- function() .Call(wrap__Rdatatype_vector__new)

Rdatatype_vector$push <- function(colname, datatype) invisible(.Call(wrap__Rdatatype_vector__push, self, colname, datatype))

Rdatatype_vector$print <- function() invisible(.Call(wrap__Rdatatype_vector__print, self))

#' @export
`$.Rdatatype_vector` <- function (self, name) { func <- Rdatatype_vector[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Rdatatype_vector` <- `$.Rdatatype_vector`

