# Generated by dev script: do not edit by hand

PY_VERSION <- "1.44.1"

DSL_SCHEMA_HASH_PY <- "9bfcd182262693be6cb872bfc62beeba38de080f9aa83767eb693044009ee6fc"
DSL_SCHEMA_HASH_CURRENT <- "9bfcd182262693be6cb872bfc62beeba38de080f9aa83767eb693044009ee6fc"
