# Generated by dev script: do not edit by hand

#' @export
`$.polars_data_frame` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_dataframe__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_dataframe__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_data_frame` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_dataframe__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_groupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_groupby__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_groupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_rolling_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_rolling_groupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_rolling_groupby__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_rolling_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_rolling_groupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_dtype` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_datatype__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_datatype__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_dtype` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_datatype__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_expr` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_expr` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_lazy_frame` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazyframe__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_lazyframe__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_lazy_frame` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazyframe__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_lazy_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazygroupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_lazygroupby__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_lazy_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazygroupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_series` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series__methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_series` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}
