# Generated by dev script: do not edit by hand

PY_VERSION <- "2.0.0rc2"

DSL_SCHEMA_HASH_PY <- "f81d616e88e2f9ceb483cd5a002ff2266cd5a57411199eedc429b2fa8e5940c0"
DSL_SCHEMA_HASH_CURRENT <- "f81d616e88e2f9ceb483cd5a002ff2266cd5a57411199eedc429b2fa8e5940c0"
