# Generated by dev script: do not edit by hand

PY_VERSION <- "1.35.1"

DSL_SCHEMA_HASH_PY <- "6286bad7b59c6dffbabcb7eda0d3a1c386cc651ad8b2479b2e4e4686199e04e1"
DSL_SCHEMA_HASH_CURRENT <- "9c14762677a5d7dd3fde8148c8968d4bec1cdada1c519b4e96f6b21fd178e13b"
