# Generated by dev script: do not edit by hand

#' @export
`$.polars_namespace_series_arr` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_arr_methods)
  dispatched_method_names <- names(polars_expr_arr_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_arr_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_arr_methods[[name]]
    expr_wrap_function_factory(fn, x, "arr")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_arr` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_arr_methods)
  dispatched_method_names <- names(polars_expr_arr_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_bin` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_bin_methods)
  dispatched_method_names <- names(polars_expr_bin_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_bin_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_bin_methods[[name]]
    expr_wrap_function_factory(fn, x, "bin")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_bin` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_bin_methods)
  dispatched_method_names <- names(polars_expr_bin_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_cat` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_cat_methods)
  dispatched_method_names <- names(polars_expr_cat_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_cat_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_cat_methods[[name]]
    expr_wrap_function_factory(fn, x, "cat")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_cat` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_cat_methods)
  dispatched_method_names <- names(polars_expr_cat_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_dt` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_dt_methods)
  dispatched_method_names <- names(polars_expr_dt_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_dt_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_dt_methods[[name]]
    expr_wrap_function_factory(fn, x, "dt")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_dt` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_dt_methods)
  dispatched_method_names <- names(polars_expr_dt_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_list` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_list_methods)
  dispatched_method_names <- names(polars_expr_list_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_list_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_list_methods[[name]]
    expr_wrap_function_factory(fn, x, "list")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_list` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_list_methods)
  dispatched_method_names <- names(polars_expr_list_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_str` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_str_methods)
  dispatched_method_names <- names(polars_expr_str_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_str_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_str_methods[[name]]
    expr_wrap_function_factory(fn, x, "str")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_str` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_str_methods)
  dispatched_method_names <- names(polars_expr_str_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_series_struct` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_struct_methods)
  dispatched_method_names <- names(polars_expr_struct_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_series_struct_methods[[name]]
    self <- x
    environment(fn) <- environment()
    fn
  } else if (name %in% dispatched_method_names) {
    fn <- polars_expr_struct_methods[[name]]
    expr_wrap_function_factory(fn, x, "struct")
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_series_struct` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_series_struct_methods)
  dispatched_method_names <- names(polars_expr_struct_methods)

  all_names <- union(member_names, method_names) |>
    union(dispatched_method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}
