# Generated by dev script: do not edit by hand

#' @export
`$.polars_data_frame` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_dataframe__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_dataframe__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_data_frame` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_dataframe__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_groupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_groupby__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_groupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_group_by_dynamic` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_group_by_dynamic__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_group_by_dynamic__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_group_by_dynamic` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_group_by_dynamic__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_rolling_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_rolling_groupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_rolling_groupby__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_rolling_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_rolling_groupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_dtype` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_datatype__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_datatype__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_dtype` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_datatype__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_expr` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_expr` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_lazy_frame` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazyframe__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_lazyframe__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_lazy_frame` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazyframe__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_lazy_group_by` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazygroupby__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_lazygroupby__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_lazy_group_by` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_lazygroupby__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_partitioning_scheme` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_partitioning_scheme__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_partitioning_scheme__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_partitioning_scheme` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_partitioning_scheme__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_sql_context` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_sql_context__methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_sql_context__methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_sql_context` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_sql_context__methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_arr` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_arr_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_arr_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_arr` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_arr_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_bin` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_bin_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_bin_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_bin` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_bin_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_cat` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_cat_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_cat_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_cat` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_cat_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_dt` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_dt_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_dt_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_dt` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_dt_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_list` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_list_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_list_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_list` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_list_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_meta` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_meta_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_meta_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_meta` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_meta_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_name` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_name_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_name_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_name` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_name_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_str` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_str_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_str_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_str` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_str_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}

#' @export
`$.polars_namespace_expr_struct` <- function(x, name) {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_struct_methods)

  if (name %in% member_names) {
    env_get(x, name)
  } else if (name %in% method_names) {
    fn <- polars_expr_struct_methods[[name]]
    self <- x # nolint: object_usage_linter
    environment(fn) <- environment()
    fn
  } else {
    NextMethod()
  }
}

#' @exportS3Method utils::.DollarNames
`.DollarNames.polars_namespace_expr_struct` <- function(x, pattern = "") {
  member_names <- ls(x, all.names = TRUE)
  method_names <- names(polars_expr_struct_methods)

  all_names <- union(member_names, method_names)
  filtered_names <- findMatches(pattern, all_names)

  filtered_names[!startsWith(filtered_names, "_")]
}
