# Input CSV functions: scan_csv, read_csv

#' Lazily read from a CSV file or multiple files via glob patterns
#'
#' This allows the query optimizer to push down predicates and projections to
#' the scan level, thereby potentially reducing memory overhead.
#'
#' @details
#' In Polars 2.0, fields supplied through `schema` are matched to CSV columns
#' by name and the file's column order is preserved. Name all elements of a
#' complete `schema` to prepare for this behavior. For `schema_overrides`, partial
#' overrides must be fully named, while a fully unnamed list must contain one
#' override for every CSV column; a mixture of named and unnamed elements is
#' not supported.
#'
#' @inherit as_polars_lf return
#' @inheritParams pl__scan_ipc
#' @inheritParams pl__scan_parquet
#' @param has_header Indicate if the first row of dataset is a header or not.If
#' `FALSE`, column names will be autogenerated in the following format:
#' `"column_x"` with `x` being an enumeration over every column in the dataset
#' starting at 1.
#' @param separator Single byte character to use as separator in the file.
#' @param comment_prefix A string, which can be up to 5 symbols in length, used
#' to indicate the start of a comment line. For instance, it can be set to `#`
#' or `//`.
#' @param quote_char Single byte character used for quoting. Set to `NULL` to
#' turn off special handling and escaping of quotes.
#' @param skip_rows Start reading after a particular number of rows. The header
#' will be parsed at this offset.
#' @param schema Provide the schema. This means that polars doesn't do schema
#' inference. This argument expects the complete schema, whereas
#' `schema_overrides` can be used to partially overwrite a schema. This must be
#' a list. Names of list elements are used to match to inferred columns.
#' @param schema_overrides Overwrite dtypes during inference. This must be a
#' list. Names of list elements are used to match to inferred columns.
#' @param null_values Character vector specifying the values to interpret as
#' `NA` values. It can be named, in which case names specify the columns in
#' which this replacement must be made (e.g. `c(col1 = "a")`).
#' @param empty_string_is_null By default, a missing string value is
#' considered to be `NA`. Setting this parameter to `FALSE` will consider
#' missing string values as an empty character instead.
#' @param missing_utf8_is_empty_string `r lifecycle::badge("deprecated")` Use
#' `empty_string_is_null` instead (note that the meaning is inverted).
#' @param ignore_errors Keep reading the file even if some lines yield errors.
#' You can also use `infer_schema = FALSE` to read all columns as UTF8 to
#' check which values might cause an issue.
#' @param cache `r lifecycle::badge("deprecated")` The Polars 2.0 streaming
#' readers do not use the file cache, and this argument has no direct
#' replacement.
#  TODO: enable this parameter
#  @param with_column_names Apply a function over the column names just in time
#  (when they are determined). This function will receive (and should return) a
#  list of column names.
#' @param infer_schema If `TRUE` (default), the schema is inferred from the
#' data using the first `infer_schema_length` rows. When `FALSE`, the schema is
#' not inferred and will be `pl$String` if not specified in `schema` or
#' `schema_overrides`.
#' @param infer_schema_length The maximum number of rows to scan for schema
#' inference. This applies individually to each file included according to
#' `infer_schema_files`. If `NULL`, the full data may be scanned (this is
#' slow). Set `infer_schema = FALSE` to read all columns as `pl$String`.
#' @param infer_schema_files `r lifecycle::badge("experimental")` How many
#' files to use when inferring the schema. In Polars 1.16, omitting this
#' argument and setting it to `NULL` uses all files. Starting with Polars 2.0,
#' the default will be 10 files. Use `infer_schema_files = 10` to opt into the
#' new default or `infer_schema_files = NULL` to keep using all files.
#' @param encoding Either `"utf8"` or `"utf8-lossy"`. Lossy means that invalid
#' UTF8 values are replaced with "?" characters.
#' @param low_memory Reduce memory pressure at the expense of performance.
#' @param skip_rows_after_header Skip this number of rows when the header is
#' parsed.
#' @param try_parse_dates Try to automatically parse dates. Most ISO8601-like
#' formats can be inferred, as well as a handful of others. If this does not
#' succeed, the column remains of data type `pl$String`.
#' @param eol_char Single byte end of line character (default: `"\n"`). When
#' encountering a file with Windows line endings (`"\r\n"`), one can go with the
#' default `"\n"`. The extra `"\r"` will be removed when processed.
#'
#  TODO: enable this parameter (requires infrastructure for with_column_names)
#  @param new_columns Provide an explicit list of string column names to use
#  (for example, when scanning a headerless CSV file). If the given list is
#  shorter than the width of the DataFrame the remaining columns will have
#  their original name.
#'
#' @param raise_if_empty If `FALSE`, parsing an empty file returns an empty
#' DataFrame or LazyFrame. Omitting this argument is deprecated because the
#' default changes conditionally in Polars 2.0: it will be `FALSE` when
#' `has_header = FALSE` and `schema` is supplied, and `TRUE` otherwise. Pass an
#' explicit value to select the desired behavior.
#' @param truncate_ragged_lines Truncate lines that are longer than the schema.
#' Its default is unchanged in Polars 1.16. In Polars 2.0, the default will be
#' determined together with the `extra_columns` CSV option.
#' @param decimal_comma Parse floats using a comma as the decimal separator
#' instead of a period.
#' @param glob Expand path given via globbing rules.
#' @examples
#' my_file <- tempfile()
#' write.csv(iris, my_file)
#' lazy_frame <- pl$scan_csv(my_file, infer_schema_files = 10)
#' lazy_frame$collect()
#' unlink(my_file)
pl__scan_csv <- function(
  source,
  ...,
  has_header = TRUE,
  separator = ",",
  comment_prefix = NULL,
  quote_char = '"',
  skip_rows = 0,
  schema = NULL,
  schema_overrides = NULL,
  null_values = NULL,
  empty_string_is_null = TRUE,
  ignore_errors = FALSE,
  cache = deprecated(),
  infer_schema = TRUE,
  infer_schema_length = 100,
  infer_schema_files = NULL,
  n_rows = NULL,
  encoding = c("utf8", "utf8-lossy"),
  low_memory = FALSE,
  rechunk = deprecated(),
  skip_rows_after_header = 0,
  row_index_name = NULL,
  row_index_offset = 0,
  try_parse_dates = FALSE,
  eol_char = "\n",
  raise_if_empty = TRUE,
  truncate_ragged_lines = FALSE,
  decimal_comma = FALSE,
  glob = TRUE,
  storage_options = NULL,
  retries = deprecated(),
  file_cache_ttl = deprecated(),
  include_file_paths = NULL,
  missing_columns = c("raise", "insert"),
  missing_utf8_is_empty_string = deprecated()
) {
  check_dots_empty0(...)
  infer_schema_files_missing <- missing(infer_schema_files)
  raise_if_empty_missing <- missing(raise_if_empty)
  check_character(source, allow_na = FALSE)
  if (length(source) == 0) {
    abort("`source` must have length > 0.")
  }
  check_list_of_polars_dtype(schema_overrides, allow_null = TRUE)
  check_list_of_polars_dtype(schema, allow_null = TRUE)
  check_character(storage_options, allow_null = TRUE)
  check_character(null_values, allow_null = TRUE)
  check_number_whole(infer_schema_files, min = 1, allow_null = TRUE)
  encoding <- arg_match0(encoding, values = c("utf8", "utf8-lossy"))
  missing_columns <- arg_match0(missing_columns, values = c("insert", "raise"))

  if (
    length(schema) > 0L &&
      (is.null(names(schema)) || anyNA(names(schema)))
  ) {
    deprecate_warn(
      c(
        `!` = sprintf(
          "Unnamed elements of %s are deprecated as of %s 1.16.0.",
          format_arg("schema"),
          format_pkg("polars")
        ),
        i = paste0(
          "In Polars 2.0, CSV schema fields will be matched to columns by name. ",
          "Name all elements of `schema` with the corresponding CSV column names."
        )
      )
    )
  }

  if (infer_schema_files_missing) {
    # TODO: @2.0: default omitted values to 10 and remove this migration path.
    warn_csv_infer_schema_files()
  }

  if (
    raise_if_empty_missing &&
      isFALSE(has_header) &&
      !is.null(schema)
  ) {
    # TODO: @2.0: resolve omission as `is.null(schema) || isTRUE(has_header)`.
    warn_csv_raise_if_empty()
  }

  if (is_present(cache)) {
    warn_deprecated_file_cache()
  } else {
    cache <- FALSE
  }

  if (is_present(missing_utf8_is_empty_string)) {
    deprecate_warn(
      c(
        `!` = sprintf(
          "The %s argument is deprecated as of %s 1.14.0.",
          format_arg("missing_utf8_is_empty_string"),
          format_pkg("polars")
        ),
        i = sprintf(
          "Use %s instead (note that the meaning is inverted).",
          format_arg("empty_string_is_null")
        )
      )
    )
    empty_string_is_null <- !missing_utf8_is_empty_string
  }

  if (is_present(retries)) {
    deprecate_warn(
      c(
        `!` = sprintf(
          "The %s argument is deprecated as of %s 1.9.0.",
          format_arg("retries"),
          format_pkg("polars")
        ),
        i = sprintf(
          "Specify %s in %s instead.",
          format_code("max_retries"),
          format_arg("storage_options")
        )
      )
    )
    storage_options <- storage_options %||% character()
    storage_options[["max_retries"]] <- as.character(retries)
  }

  if (is_present(file_cache_ttl)) {
    warn_deprecated_file_cache_ttl()
  }

  if (isFALSE(infer_schema)) {
    infer_schema_length <- 0
  }

  schema_overrides <- parse_into_list_of_datatypes(!!!schema_overrides)

  if (!is.null(schema)) {
    schema <- parse_into_list_of_datatypes(!!!schema)
  }

  if (is_present(rechunk)) {
    warn_deprecated_rechunk()
  } else {
    rechunk <- FALSE
  }

  PlRLazyFrame$new_from_csv(
    source = source,
    separator = separator,
    has_header = has_header,
    ignore_errors = ignore_errors,
    skip_rows = skip_rows,
    cache = cache,
    missing_utf8_is_empty_string = !empty_string_is_null,
    low_memory = low_memory,
    rechunk = rechunk,
    skip_rows_after_header = skip_rows_after_header,
    encoding = encoding,
    try_parse_dates = try_parse_dates,
    eol_char = eol_char,
    raise_if_empty = raise_if_empty,
    # TODO: @2.0: derive omission from `extra_columns == "ignore"` and reject
    # an explicit `FALSE` when that option requests truncation.
    truncate_ragged_lines = truncate_ragged_lines,
    decimal_comma = decimal_comma,
    glob = glob,
    comment_prefix = comment_prefix,
    quote_char = quote_char,
    null_values = null_values,
    infer_schema_length = infer_schema_length,
    infer_schema_files = infer_schema_files,
    row_index_name = row_index_name,
    row_index_offset = row_index_offset,
    n_rows = n_rows,
    overwrite_dtype = schema_overrides,
    schema = schema,
    storage_options = storage_options,
    include_file_paths = include_file_paths,
    missing_columns = missing_columns
  ) |>
    wrap()
}

#' New DataFrame from CSV
#' @inheritParams pl__scan_csv
#' @inherit pl__scan_csv details
#' @inherit as_polars_df return
#' @examples
#' my_file <- tempfile()
#' write.csv(iris, my_file)
#' pl$read_csv(my_file, infer_schema_files = 10)
#' unlink(my_file)
pl__read_csv <- function(
  source,
  ...,
  has_header = TRUE,
  separator = ",",
  comment_prefix = NULL,
  quote_char = '"',
  skip_rows = 0,
  schema = NULL,
  schema_overrides = NULL,
  null_values = NULL,
  empty_string_is_null = TRUE,
  ignore_errors = FALSE,
  cache = deprecated(),
  infer_schema = TRUE,
  infer_schema_length = 100,
  infer_schema_files = NULL,
  n_rows = NULL,
  encoding = c("utf8", "utf8-lossy"),
  low_memory = FALSE,
  rechunk = deprecated(),
  skip_rows_after_header = 0,
  row_index_name = NULL,
  row_index_offset = 0,
  try_parse_dates = FALSE,
  eol_char = "\n",
  raise_if_empty = TRUE,
  truncate_ragged_lines = FALSE,
  decimal_comma = FALSE,
  glob = TRUE,
  storage_options = NULL,
  retries = deprecated(),
  file_cache_ttl = deprecated(),
  include_file_paths = NULL,
  missing_columns = c("raise", "insert"),
  missing_utf8_is_empty_string = deprecated()
) {
  check_dots_empty0(...)
  .args <- as.list(environment())
  if (missing(infer_schema_files)) {
    # TODO: @2.0: remove when the formal default changes to 10.
    .args$infer_schema_files <- missing_arg()
  }
  if (missing(raise_if_empty)) {
    # TODO: @2.0: retain for the conditional default.
    .args$raise_if_empty <- missing_arg()
  }
  if (missing(truncate_ragged_lines)) {
    # TODO: @2.0: retain for the `extra_columns`-dependent default.
    .args$truncate_ragged_lines <- missing_arg()
  }
  do.call(pl$scan_csv, .args)$collect() |>
    wrap()
}
