name: Test R-universe

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/r-universe-test.yml
      - R/**
      - src/**
      - tests/**
      - tools/**
      - vignettes/*
      - configure*
      - DESCRIPTION
      - NAMESPACE
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/r-universe-test.yml
      - R/**
      - src/**
      - tests/**
      - tools/**
      - vignettes/*
      - configure*
      - DESCRIPTION
      - NAMESPACE
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  LIB_SUMS_PATH: "tools/lib-sums.tsv"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check for pre-built binary
    outputs:
      has_binary: ${{ steps.check.outputs.has_binary }}
    steps:
      - uses: actions/checkout@v6

      - name: Check for pre-built binary
        id: check
        run: |
          if [[ -f "${LIB_SUMS_PATH}" ]]; then
            echo "has_binary=true" >>"${GITHUB_OUTPUT}"
          else
            echo "has_binary=false" >>"${GITHUB_OUTPUT}"
          fi

  build:
    needs: check
    if: needs.check.outputs.has_binary == 'true'
    name: R-universe tests
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
